In [63]:
# 1. PCA dataset
import pandas as pd

df = pd.read_csv('../../mestrado/CalculosAnna/Sensor/baseAllSensorsMinusResParal.csv')
print(df)

# df['Sensor'] = df['Sensor'].astype('string')
df.head()

     Sensor  Electrode  Param  microg/ml      1.00E+06      7.94E+05  \
0       1.0        6.0    1.0      0.001  7.260000e+01  7.280000e+01   
1       1.0        6.0    1.0      0.100  7.250000e+01  7.270000e+01   
2       1.0        1.0    1.0      0.001  1.110000e+02  1.120000e+02   
3       1.0        1.0    1.0      0.010  1.100000e+02  1.120000e+02   
4       1.0        1.0    1.0      0.100  1.100000e+02  1.120000e+02   
..      ...        ...    ...        ...           ...           ...   
145     2.0        2.0    6.0      0.010 -8.710000e-08  3.960000e-08   
146     2.0        2.0    6.0      0.020 -9.130000e-08  3.860000e-08   
147     2.0        2.0    6.0      0.100 -9.130000e-08  3.850000e-08   
148     2.0        2.0    6.0      0.200 -1.550000e-07  3.270000e-08   
149     2.0        2.0    6.0      1.000 -2.390000e-07  3.020000e-08   

         6.31E+05      5.01E+05      3.98E+05      3.16E+05  ...  \
0    7.290000e+01  7.310000e+01  7.340000e+01  7.380000e+01  ...   

Sensor  Electrode  Param  microg/ml  1.00E+06  7.94E+05  6.31E+05  \
0     1.0        6.0    1.0      0.001      72.6      72.8      72.9   
1     1.0        6.0    1.0      0.100      72.5      72.7      72.8   
2     1.0        1.0    1.0      0.001     111.0     112.0     114.0   
3     1.0        1.0    1.0      0.010     110.0     112.0     113.0   
4     1.0        1.0    1.0      0.100     110.0     112.0     113.0   

   5.01E+05  3.98E+05  3.16E+05  ...  7.94E+00  6.31E+00  5.01E+00  3.98E+00  \
0      73.1      73.4      73.8  ...   16900.0   21000.0   25900.0   31700.0   
1      73.0      73.3      73.7  ...   16800.0   20700.0   25500.0   31200.0   
2     116.0     119.0     123.0  ...  182000.0  220000.0  259000.0  298000.0   
3     116.0     118.0     122.0  ...  169000.0  204000.0  242000.0  281000.0   
4     116.0     119.0     122.0  ...  170000.0  206000.0  244000.0  283000.0   

   3.16E+00  2.51E+00  2.00E+00  1.58E+00  1.26E+00  1.00E+00  
0   38600.0   46500.0   55400.0   65400.0   76500.0   88600.0  
1   37800.0   45700.0   54600.0   64800.0   76200.0   89100.0  
2  337000.0  372000.0  402000.0  428000.0  449000.0  467000.0  
3  319000.0  353000.0  383000.0  411000.0  433000.0  451000.0  
4  320000.0  355000.0  386000.0  413000.0  435000.0  454000.0  

[5 rows x 65 columns]

In [64]:
print(df.dtypes)

Sensor       float64
Electrode    float64
Param        float64
microg/ml    float64
1.00E+06     float64
              ...   
2.51E+00     float64
2.00E+00     float64
1.58E+00     float64
1.26E+00     float64
1.00E+00     float64
Length: 65, dtype: object


In [65]:
df_features = df.iloc[:,1:].copy()
X = df_features.to_numpy()
# X = df.values
X

array([[6.00e+00, 1.00e+00, 1.00e-03, ..., 6.54e+04, 7.65e+04, 8.86e+04],
       [6.00e+00, 1.00e+00, 1.00e-01, ..., 6.48e+04, 7.62e+04, 8.91e+04],
       [1.00e+00, 1.00e+00, 1.00e-03, ..., 4.28e+05, 4.49e+05, 4.67e+05],
       ...,
       [2.00e+00, 6.00e+00, 1.00e-01, ..., 3.67e-08, 4.01e-08, 4.49e-08],
       [2.00e+00, 6.00e+00, 2.00e-01, ..., 3.65e-08, 4.04e-08, 4.50e-08],
       [2.00e+00, 6.00e+00, 1.00e+00, ..., 3.50e-08, 3.87e-08, 4.24e-08]])

In [66]:
Y = df.iloc[:, 0].to_numpy()
Y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [67]:
X.shape

(150, 64)

In [68]:
Y.shape

(150,)

In [69]:
# 2. PCA analysis
# 2.1 Load library

from sklearn.preprocessing import scale # Data scaling
from sklearn import decomposition # PCA
import pandas as pd # pandas

In [70]:
# 2.2 Data scaling
x = scale(X)

# Standardize the Data
# PCA is effected by scale so you need to scale the features in your data before applying PCA. Use StandardScaler to help you standardize the dataset’s features onto unit scale (mean = 0 and variance = 1) which is a requirement for the optimal performance of many machine learning algorithms.
x

array([[ 2.62202212, -1.27872403, -0.62350062, ...,  0.38783369,
         0.38164042,  0.37233809],
       [ 2.62202212, -1.27872403, -0.36555427, ...,  0.38652551,
         0.38110217,  0.37307257],
       [-0.95346259, -1.27872403, -0.62350062, ...,  1.17840846,
         1.04996688,  0.92819667],
       ...,
       [-0.23836565,  1.62746694, -0.36555427, ...,  0.24524243,
         0.2443868 ,  0.24218727],
       [-0.23836565,  1.62746694, -0.1050024 , ...,  0.24524243,
         0.2443868 ,  0.24218727],
       [-0.23836565,  1.62746694,  1.97941253, ...,  0.24524243,
         0.2443868 ,  0.24218727]])

In [71]:
# 2.3 Perform PCA analysis
pca = decomposition.PCA(n_components=2)
pca.fit(x) # when build the model we use pca.fit function. Where by the argument will be the input data, which essencially is the x variable
# we are using the x variable because pca is an unsupervised learning approach, meaning that it does not need the y variable or the class label in order to learn
# it`ll goind to cluster the data based on similarity and differences, based on the eigenvalue that are inherently present in the data set

PCA(n_components=2)

In [72]:
# 2.4 compure the scores value
# scores value will essentially be represented by the data samples so we`re gonna use the pca.transform function
scores = pca.transform(x)

In [73]:
scores

array([[ -4.24115986,   1.02101838],
       [ -4.22914398,   1.01895514],
       [ -9.79417419,   0.99506979],
       [ -9.51449394,   1.07897695],
       [ -9.50293935,   1.04123784],
       [ -9.84598855,   0.94743651],
       [ -5.74832205,   1.19706516],
       [ -5.62266796,   1.1541534 ],
       [ -5.63404187,   1.11301034],
       [ -5.76477887,   1.10412037],
       [ -5.44060686,   0.5164277 ],
       [ -5.58372317,   0.41590106],
       [ -5.64125138,   0.32613155],
       [ -5.80042481,   0.26609569],
       [ -6.09020062,   1.04550394],
       [ -6.09414574,   1.05079318],
       [ -6.09472854,   1.03592323],
       [ -6.17961171,   0.99382292],
       [  2.25255555,  -1.13189038],
       [  2.27992792,  -1.11113068],
       [ 14.74265043,   1.98935878],
       [ 13.97119087,   1.76164688],
       [ 14.06086184,   1.84521292],
       [ 14.89007509,   1.95370386],
       [  5.46890124,  -1.02167345],
       [  5.28793777,  -0.95674366],
       [  5.42296679,  -0.8715619 ],
 

In [74]:
scores_df = pd.DataFrame(scores, columns=['PC1', 'PC2']) # dataframe is to make more readable
scores_df

PC1       PC2
0   -4.241160  1.021018
1   -4.229144  1.018955
2   -9.794174  0.995070
3   -9.514494  1.078977
4   -9.502939  1.041238
..        ...       ...
145 -1.286897 -1.871803
146 -1.286831 -1.871782
147 -1.286309 -1.871616
148 -1.285656 -1.871409
149 -1.280433 -1.869752

[150 rows x 2 columns]

In [75]:
y_label = []

for i in Y:
    if i == 1:
        y_label.append('HCV')
    else:
        y_label.append('HIV')

sensors = pd.DataFrame(y_label, columns=['Sensor'])

In [76]:
df_scores = pd.concat([scores_df, sensors], axis=1) # combine dataframes with concat
df_scores

PC1       PC2 Sensor
0   -4.241160  1.021018    HCV
1   -4.229144  1.018955    HCV
2   -9.794174  0.995070    HCV
3   -9.514494  1.078977    HCV
4   -9.502939  1.041238    HCV
..        ...       ...    ...
145 -1.286897 -1.871803    HIV
146 -1.286831 -1.871782    HIV
147 -1.286309 -1.871616    HIV
148 -1.285656 -1.871409    HIV
149 -1.280433 -1.869752    HIV

[150 rows x 3 columns]

In [77]:
feature_names = df.columns[1:]
feature_names

Index(['Electrode', 'Param', 'microg/ml', '1.00E+06', '7.94E+05', '6.31E+05',
       '5.01E+05', '3.98E+05', '3.16E+05', '2.51E+05', '2.00E+05', '1.58E+05',
       '1.26E+05', '1.00E+05', '7.94E+04', '6.31E+04', '5.01E+04', '3.98E+04',
       '3.16E+04', '2.51E+04', '2.00E+04', '1.58E+04', '1.26E+04', '1.00E+04',
       '7.94E+03', '6.31E+03', '5.01E+03', '3.98E+03', '3.16E+03', '2.51E+03',
       '2.00E+03', '1.58E+03', '1.26E+03', '1.00E+03', '7.94E+02', '6.31E+02',
       '5.01E+02', '3.98E+02', '3.16E+02', '2.51E+02', '2.00E+02', '1.58E+02',
       '1.26E+02', '1.00E+02', '7.94E+01', '6.31E+01', '5.01E+01', '3.98E+01',
       '3.16E+01', '2.51E+01', '2.00E+01', '1.58E+01', '1.26E+01', '1.00E+01',
       '7.94E+00', '6.31E+00', '5.01E+00', '3.98E+00', '3.16E+00', '2.51E+00',
       '2.00E+00', '1.58E+00', '1.26E+00', '1.00E+00'],
      dtype='object')

In [78]:
# 2.5 retrieve the loading values (remember PCA scores and loadings)
# loadings value tell about the descriptor and scores value tell about the data samples
# 150 flowers 150 score values 4 descriptors 4 loading values (1 for each descriptor)
loadings = pca.components_.T
df_loadings = pd.DataFrame(loadings, columns=['PC1', 'PC2'], index=feature_names)
df_loadings

PC1       PC2
Electrode -0.002818 -0.069638
Param     -0.002491 -0.170658
microg/ml  0.002506  0.000795
1.00E+06  -0.072128  0.259784
7.94E+05  -0.076246  0.254843
...             ...       ...
2.51E+00  -0.128786 -0.081101
2.00E+00  -0.127426 -0.080285
1.58E+00  -0.126118 -0.079212
1.26E+00  -0.124911 -0.078595
1.00E+00  -0.123746 -0.077792

[64 rows x 2 columns]

In [79]:
# 2.6 explained variance
# what`s the contribuition to the percent variance of the entire model contributed by each of the principal components
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.75775149, 0.16858851])

In [80]:
# 3. Scree plot
import numpy as np
import plotly.express as px

In [81]:
# 3.1 preparing the explained variance data
# add origin value, x and y are going to have origin zero, the subsequent lines of code are going to create the scree plot
# the scree plot does not start from zero, then we need to manually create the zero origin
explained_variance = np.insert(explained_variance, 0, 0)
explained_variance

array([0.        , 0.75775149, 0.16858851])

In [82]:
# 3.2 Preparing cumulative variance data
cumulative_variance = np.cumsum(np.round(explained_variance, decimals=3))

In [83]:
# 3.3 Combining dataframe
pc_df = pd.DataFrame(['', 'PC1', 'PC2'], columns=['PC'])
explained_variance_df = pd.DataFrame(explained_variance, columns=['Explained Variance'])
cumulative_variance_df = pd.DataFrame(cumulative_variance, columns=['Cumulative Variance'])

In [84]:
df_explained_variance = pd.concat([pc_df, explained_variance_df, cumulative_variance_df], axis=1)
df_explained_variance

PC  Explained Variance  Cumulative Variance
0                 0.000000                0.000
1  PC1            0.757751                0.758
2  PC2            0.168589                0.927

In [85]:
# 3.4 Creating Scree Plot
# https://plotly.com/python/bar-charts/

fig = px.bar(df_explained_variance, x='PC', y='Explained Variance', text='Explained Variance', width=800)

In [86]:
fig.update_traces(texttemplate='%{text:.3f}', textposition='outside') # limit decimal cases and text outside the bar
fig.show() #explained variance

In [87]:
# explained variance + cumulative variance
# https://plotly.com/python/creating-and-updating-figures

import plotly.graph_objects as go
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ))

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ))

fig.show()

In [88]:
# Explained variance + cumulative variance (Separate Plot)

from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=1, cols=2)

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ), row=1, col=1
)

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ), row=1, col=2
)

fig.show()

In [90]:
# 4. Scores plot
# check API documentation for plotly.express https://plotly.com/python/3d-scatter-plots

import plotly.express as px

fig = px.scatter(df_scores, x='PC1', y='PC2', color='Sensor')
fig.show()

In [91]:
# 4.1 Customize 3D Scatter Plot

fig = px.scatter(df_scores, x='PC1', y='PC2', color='Sensor', symbol='Sensor', opacity=0.3)

# tight layout
fig.update_layout(margin=dict(l=0, r=0, b=0, t=0)) # left, right, bottom, top with zero margin

fig.show()

# https://plotly.com/python/templates/
# fig.update_layout(template='plotly_white')
# plotly, plotly_white, plotly_dark, ggplot2, seaborn, simple_white, none

In [92]:
# 5. Loadings Plot

loadings_label = df_loadings.index
# loadings_label = df_loadings.index.str.strip(' (cm)')

fig = px.scatter(df_loadings, x='PC1', y='PC2', text=loadings_label)
fig.show()

In [93]:
loadings_label

Index(['Electrode', 'Param', 'microg/ml', '1.00E+06', '7.94E+05', '6.31E+05',
       '5.01E+05', '3.98E+05', '3.16E+05', '2.51E+05', '2.00E+05', '1.58E+05',
       '1.26E+05', '1.00E+05', '7.94E+04', '6.31E+04', '5.01E+04', '3.98E+04',
       '3.16E+04', '2.51E+04', '2.00E+04', '1.58E+04', '1.26E+04', '1.00E+04',
       '7.94E+03', '6.31E+03', '5.01E+03', '3.98E+03', '3.16E+03', '2.51E+03',
       '2.00E+03', '1.58E+03', '1.26E+03', '1.00E+03', '7.94E+02', '6.31E+02',
       '5.01E+02', '3.98E+02', '3.16E+02', '2.51E+02', '2.00E+02', '1.58E+02',
       '1.26E+02', '1.00E+02', '7.94E+01', '6.31E+01', '5.01E+01', '3.98E+01',
       '3.16E+01', '2.51E+01', '2.00E+01', '1.58E+01', '1.26E+01', '1.00E+01',
       '7.94E+00', '6.31E+00', '5.01E+00', '3.98E+00', '3.16E+00', '2.51E+00',
       '2.00E+00', '1.58E+00', '1.26E+00', '1.00E+00'],
      dtype='object')

In [94]:
df_loadings

PC1       PC2
Electrode -0.002818 -0.069638
Param     -0.002491 -0.170658
microg/ml  0.002506  0.000795
1.00E+06  -0.072128  0.259784
7.94E+05  -0.076246  0.254843
...             ...       ...
2.51E+00  -0.128786 -0.081101
2.00E+00  -0.127426 -0.080285
1.58E+00  -0.126118 -0.079212
1.26E+00  -0.124911 -0.078595
1.00E+00  -0.123746 -0.077792

[64 rows x 2 columns]

In [95]:
df_loadings.sort_values(by='PC1',ascending=False)

PC1       PC2
microg/ml  0.002506  0.000795
Param     -0.002491 -0.170658
Electrode -0.002818 -0.069638
1.00E+06  -0.072128  0.259784
7.94E+05  -0.076246  0.254843
...             ...       ...
3.16E+03  -0.140046 -0.028501
7.94E+03  -0.140509  0.032878
3.98E+03  -0.140551 -0.015693
5.01E+03  -0.140886 -0.001064
6.31E+03  -0.140911  0.015317

[64 rows x 2 columns]

In [96]:
df_loadings.sort_values(by='PC2',ascending=False)

PC1       PC2
1.00E+06 -0.072128  0.259784
7.94E+05 -0.076246  0.254843
6.31E+05 -0.080123  0.249825
5.01E+05 -0.083994  0.244429
3.98E+05 -0.087970  0.238466
...            ...       ...
7.94E+01 -0.136460 -0.090002
3.98E+01 -0.136667 -0.090153
6.31E+01 -0.136534 -0.090229
5.01E+01 -0.136611 -0.090247
Param    -0.002491 -0.170658

[64 rows x 2 columns]