In [1142]:
# 1. PCA dataset
import pandas as pd

df = pd.read_csv('../../mestrado/CalculosAnna/Sensor/baseAllSensorsTest5.csv')
print(df)

# df['Sensor'] = df['Sensor'].astype('string')
df.head()

    Sensor  Param  microg/ml      5.01E+05      3.98E+05      3.16E+05  \
0      1.0    1.0      0.001  7.310000e+01  7.340000e+01  7.380000e+01   
1      1.0    1.0      0.001  1.160000e+02  1.190000e+02  1.230000e+02   
2      1.0    1.0      0.010  1.160000e+02  1.180000e+02  1.220000e+02   
3      1.0    1.0      0.001  7.400000e+01  7.660000e+01  7.980000e+01   
4      1.0    1.0      0.010  7.390000e+01  7.630000e+01  7.940000e+01   
..     ...    ...        ...           ...           ...           ...   
70     2.0    6.0      0.010  3.780000e-08  2.290000e-08  1.850000e-08   
71     2.0    6.0      0.020  3.670000e-08  2.240000e-08  1.820000e-08   
72     2.0    6.0      0.002  1.450000e-08  1.200000e-08  1.070000e-08   
73     2.0    6.0      0.010  1.400000e-08  1.160000e-08  1.040000e-08   
74     2.0    6.0      0.020  1.390000e-08  1.150000e-08  1.030000e-08   

        2.51E+05      2.00E+05      1.58E+05      1.26E+05  ...      6.31E+04  \
0   7.440000e+01  7.530000e+01

Sensor  Param  microg/ml  5.01E+05  3.98E+05  3.16E+05  2.51E+05  2.00E+05  \
0     1.0    1.0      0.001      73.1      73.4      73.8      74.4      75.3   
1     1.0    1.0      0.001     116.0     119.0     123.0     128.0     134.0   
2     1.0    1.0      0.010     116.0     118.0     122.0     127.0     132.0   
3     1.0    1.0      0.001      74.0      76.6      79.8      83.8      88.6   
4     1.0    1.0      0.010      73.9      76.3      79.4      83.2      87.7   

   1.58E+05  1.26E+05  ...  6.31E+04  5.01E+04  3.98E+04  3.16E+04  2.51E+04  \
0      76.6      78.5  ...      89.6      96.4     105.0     116.0     128.0   
1     142.0     150.0  ...     182.0     193.0     204.0     214.0     224.0   
2     139.0     148.0  ...     178.0     189.0     200.0     211.0     221.0   
3      94.3     101.0  ...     126.0     135.0     145.0     156.0     168.0   
4      93.1      99.3  ...     122.0     131.0     140.0     150.0     161.0   

   2.00E+04  1.58E+04  1.26E+04  1.00E+04  7.94E+03  
0     143.0     157.0     172.0     186.0     198.0  
1     235.0     246.0     258.0     273.0     291.0  
2     232.0     243.0     255.0     270.0     288.0  
3     181.0     196.0     212.0     232.0     256.0  
4     173.0     187.0     202.0     221.0     242.0  

[5 rows x 22 columns]

In [1143]:
print(df.dtypes)

Sensor       float64
Param        float64
microg/ml    float64
5.01E+05     float64
3.98E+05     float64
3.16E+05     float64
2.51E+05     float64
2.00E+05     float64
1.58E+05     float64
1.26E+05     float64
1.00E+05     float64
7.94E+04     float64
6.31E+04     float64
5.01E+04     float64
3.98E+04     float64
3.16E+04     float64
2.51E+04     float64
2.00E+04     float64
1.58E+04     float64
1.26E+04     float64
1.00E+04     float64
7.94E+03     float64
dtype: object


In [1144]:
df_features = df.iloc[:,1:].copy()
X = df_features.to_numpy()
# X = df.values
X

array([[1.00e+00, 1.00e-03, 7.31e+01, ..., 1.72e+02, 1.86e+02, 1.98e+02],
       [1.00e+00, 1.00e-03, 1.16e+02, ..., 2.58e+02, 2.73e+02, 2.91e+02],
       [1.00e+00, 1.00e-02, 1.16e+02, ..., 2.55e+02, 2.70e+02, 2.88e+02],
       ...,
       [6.00e+00, 2.00e-03, 1.45e-08, ..., 1.10e-08, 1.02e-08, 9.47e-09],
       [6.00e+00, 1.00e-02, 1.40e-08, ..., 1.07e-08, 9.99e-09, 9.22e-09],
       [6.00e+00, 2.00e-02, 1.39e-08, ..., 1.08e-08, 1.01e-08, 9.33e-09]])

In [1145]:
Y = df.iloc[:, 0].to_numpy()
Y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2.])

In [1146]:
X.shape

(75, 21)

In [1147]:
Y.shape

(75,)

In [1148]:
# 2. PCA analysis
# 2.1 Load library

from sklearn.preprocessing import scale # Data scaling
from sklearn import decomposition # PCA
import pandas as pd # pandas

In [1149]:
# 2.2 Data scaling
x = scale(X)

# Standardize the Data
# PCA is effected by scale so you need to scale the features in your data before applying PCA. Use StandardScaler to help you standardize the dataset’s features onto unit scale (mean = 0 and variance = 1) which is a requirement for the optimal performance of many machine learning algorithms.
x

array([[-1.62746694, -0.97400175, -0.44619717, ..., -0.45178067,
        -0.44521035, -0.43895776],
       [-1.62746694, -0.97400175, -0.44619565, ..., -0.45177785,
        -0.44520764, -0.43895502],
       [-1.62746694,  0.42483055, -0.44619565, ..., -0.45177795,
        -0.44520773, -0.43895511],
       ...,
       [ 1.27872403, -0.81857594, -0.44619975, ..., -0.4517863 ,
        -0.44521616, -0.43896358],
       [ 1.27872403,  0.42483055, -0.44619975, ..., -0.4517863 ,
        -0.44521616, -0.43896358],
       [ 1.27872403,  1.97908866, -0.44619975, ..., -0.4517863 ,
        -0.44521616, -0.43896358]])

In [1150]:
# 2.3 Perform PCA analysis
pca = decomposition.PCA(n_components=2)
pca.fit(x) # when build the model we use pca.fit function. Where by the argument will be the input data, which essencially is the x variable
# we are using the x variable because pca is an unsupervised learning approach, meaning that it does not need the y variable or the class label in order to learn
# it`ll goind to cluster the data based on similarity and differences, based on the eigenvalue that are inherently present in the data set

PCA(n_components=2)

In [1151]:
# 2.4 compure the scores value
# scores value will essentially be represented by the data samples so we`re gonna use the pca.transform function
scores = pca.transform(x)

In [1152]:
scores

array([[-2.13135742, -0.95550119],
       [-2.13134758, -0.95550108],
       [-2.13062796,  0.44161947],
       [-2.13135373, -0.9555011 ],
       [-2.13063441,  0.44161943],
       [-2.13135399, -0.95550098],
       [-2.13063393,  0.4416196 ],
       [-2.13135201, -0.95550099],
       [-2.13063202,  0.44161958],
       [-2.04018807, -0.96784399],
       [-2.04018807, -0.96784399],
       [-2.03946813,  0.42927657],
       [-2.04018807, -0.96784399],
       [-2.03946813,  0.42927657],
       [-2.04018807, -0.96784399],
       [-2.03946813,  0.42927657],
       [-2.04018807, -0.96784399],
       [-2.03946813,  0.42927657],
       [-1.99459634, -0.97401523],
       [-1.99459634, -0.97401523],
       [-1.99387641,  0.42310532],
       [-1.99459634, -0.97401523],
       [-1.99387641,  0.42310532],
       [-1.99459634, -0.97401523],
       [-1.99387641,  0.42310532],
       [-1.99459634, -0.97401523],
       [-1.99387641,  0.42310532],
       [ 1.03464401, -0.97249402],
       [12.33608815,

In [1153]:
scores_df = pd.DataFrame(scores, columns=['PC1', 'PC2']) # dataframe is to make more readable
scores_df

PC1       PC2
0  -2.131357 -0.955501
1  -2.131348 -0.955501
2  -2.130628  0.441619
3  -2.131354 -0.955501
4  -2.130634  0.441619
..       ...       ...
70 -1.902693  0.410763
71 -1.901893  1.963119
72 -1.903333 -0.831122
73 -1.902693  0.410763
74 -1.901893  1.963119

[75 rows x 2 columns]

In [1154]:
y_label = []

for i in Y:
    if i == 1:
        y_label.append('HCV')
    else:
        y_label.append('HIV')

sensors = pd.DataFrame(y_label, columns=['Sensor'])

In [1155]:
df_scores = pd.concat([scores_df, sensors], axis=1) # combine dataframes with concat
df_scores

PC1       PC2 Sensor
0  -2.131357 -0.955501    HCV
1  -2.131348 -0.955501    HCV
2  -2.130628  0.441619    HCV
3  -2.131354 -0.955501    HCV
4  -2.130634  0.441619    HCV
..       ...       ...    ...
70 -1.902693  0.410763    HIV
71 -1.901893  1.963119    HIV
72 -1.903333 -0.831122    HIV
73 -1.902693  0.410763    HIV
74 -1.901893  1.963119    HIV

[75 rows x 3 columns]

In [1156]:
feature_names = df.columns[1:]
feature_names

Index(['Param', 'microg/ml', '5.01E+05', '3.98E+05', '3.16E+05', '2.51E+05',
       '2.00E+05', '1.58E+05', '1.26E+05', '1.00E+05', '7.94E+04', '6.31E+04',
       '5.01E+04', '3.98E+04', '3.16E+04', '2.51E+04', '2.00E+04', '1.58E+04',
       '1.26E+04', '1.00E+04', '7.94E+03'],
      dtype='object')

In [1157]:
# 2.5 retrieve the loading values (remember PCA scores and loadings)
# loadings value tell about the descriptor and scores value tell about the data samples
# 150 flowers 150 score values 4 descriptors 4 loading values (1 for each descriptor)
loadings = pca.components_.T
df_loadings = pd.DataFrame(loadings, columns=['PC1', 'PC2'], index=feature_names)
df_loadings

PC1       PC2
Param      0.078439 -0.010617
microg/ml  0.000515  0.998776
5.01E+05   0.226689 -0.015985
3.98E+05   0.228903 -0.010502
3.16E+05   0.229539 -0.008578
2.51E+05   0.229774 -0.007748
2.00E+05   0.229774 -0.007423
1.58E+05   0.229653 -0.006847
1.26E+05   0.229381 -0.007101
1.00E+05   0.229155 -0.006716
7.94E+04   0.228992 -0.006042
6.31E+04   0.229010 -0.004769
5.01E+04   0.229264 -0.003759
3.98E+04   0.229699 -0.001458
3.16E+04   0.230130  0.001197
2.51E+04   0.230226  0.004736
2.00E+04   0.229773  0.008760
1.58E+04   0.228692  0.012738
1.26E+04   0.227200  0.016884
1.00E+04   0.225560  0.020809
7.94E+03   0.223945  0.024078

In [1158]:
# 2.6 explained variance
# what`s the contribuition to the percent variance of the entire model contributed by each of the principal components
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.89583718, 0.04771033])

In [1159]:
# 3. Scree plot
import numpy as np
import plotly.express as px

In [1160]:
# 3.1 preparing the explained variance data
# add origin value, x and y are going to have origin zero, the subsequent lines of code are going to create the scree plot
# the scree plot does not start from zero, then we need to manually create the zero origin
explained_variance = np.insert(explained_variance, 0, 0)
explained_variance

array([0.        , 0.89583718, 0.04771033])

In [1161]:
# 3.2 Preparing cumulative variance data
cumulative_variance = np.cumsum(np.round(explained_variance, decimals=3))

In [1162]:
# 3.3 Combining dataframe
pc_df = pd.DataFrame(['', 'PC1', 'PC2'], columns=['PC'])
explained_variance_df = pd.DataFrame(explained_variance, columns=['Explained Variance'])
cumulative_variance_df = pd.DataFrame(cumulative_variance, columns=['Cumulative Variance'])

In [1163]:
df_explained_variance = pd.concat([pc_df, explained_variance_df, cumulative_variance_df], axis=1)
df_explained_variance

PC  Explained Variance  Cumulative Variance
0                 0.000000                0.000
1  PC1            0.895837                0.896
2  PC2            0.047710                0.944

In [1164]:
# 3.4 Creating Scree Plot
# https://plotly.com/python/bar-charts/

fig = px.bar(df_explained_variance, x='PC', y='Explained Variance', text='Explained Variance', width=800)

In [1165]:
fig.update_traces(texttemplate='%{text:.3f}', textposition='outside') # limit decimal cases and text outside the bar
fig.show() #explained variance

In [1166]:
# explained variance + cumulative variance
# https://plotly.com/python/creating-and-updating-figures

import plotly.graph_objects as go
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ))

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ))

fig.show()

In [1167]:
# Explained variance + cumulative variance (Separate Plot)

from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=1, cols=2)

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ), row=1, col=1
)

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ), row=1, col=2
)

fig.show()

In [1168]:
# 4. Scores plot
# check API documentation for plotly.express https://plotly.com/python/3d-scatter-plots

import plotly.express as px

fig = px.scatter(df_scores, x='PC1', y='PC2', color='Sensor')
fig.show()

In [1169]:
# 4.1 Customize 3D Scatter Plot

fig = px.scatter(df_scores, x='PC1', y='PC2', color='Sensor', symbol='Sensor', opacity=0.3)

# tight layout
fig.update_layout(margin=dict(l=0, r=0, b=0, t=0)) # left, right, bottom, top with zero margin

fig.show()

# https://plotly.com/python/templates/
# fig.update_layout(template='plotly_white')
# plotly, plotly_white, plotly_dark, ggplot2, seaborn, simple_white, none

In [1170]:
# 5. Loadings Plot

loadings_label = df_loadings.index
# loadings_label = df_loadings.index.str.strip(' (cm)')

fig = px.scatter(df_loadings, x='PC1', y='PC2', text=loadings_label)
fig.show()

In [1171]:
loadings_label

Index(['Param', 'microg/ml', '5.01E+05', '3.98E+05', '3.16E+05', '2.51E+05',
       '2.00E+05', '1.58E+05', '1.26E+05', '1.00E+05', '7.94E+04', '6.31E+04',
       '5.01E+04', '3.98E+04', '3.16E+04', '2.51E+04', '2.00E+04', '1.58E+04',
       '1.26E+04', '1.00E+04', '7.94E+03'],
      dtype='object')

In [1172]:
df_loadings

PC1       PC2
Param      0.078439 -0.010617
microg/ml  0.000515  0.998776
5.01E+05   0.226689 -0.015985
3.98E+05   0.228903 -0.010502
3.16E+05   0.229539 -0.008578
2.51E+05   0.229774 -0.007748
2.00E+05   0.229774 -0.007423
1.58E+05   0.229653 -0.006847
1.26E+05   0.229381 -0.007101
1.00E+05   0.229155 -0.006716
7.94E+04   0.228992 -0.006042
6.31E+04   0.229010 -0.004769
5.01E+04   0.229264 -0.003759
3.98E+04   0.229699 -0.001458
3.16E+04   0.230130  0.001197
2.51E+04   0.230226  0.004736
2.00E+04   0.229773  0.008760
1.58E+04   0.228692  0.012738
1.26E+04   0.227200  0.016884
1.00E+04   0.225560  0.020809
7.94E+03   0.223945  0.024078

In [1173]:
df_loadings.sort_values(by='PC1',ascending=False)

PC1       PC2
2.51E+04   0.230226  0.004736
3.16E+04   0.230130  0.001197
2.00E+05   0.229774 -0.007423
2.51E+05   0.229774 -0.007748
2.00E+04   0.229773  0.008760
3.98E+04   0.229699 -0.001458
1.58E+05   0.229653 -0.006847
3.16E+05   0.229539 -0.008578
1.26E+05   0.229381 -0.007101
5.01E+04   0.229264 -0.003759
1.00E+05   0.229155 -0.006716
6.31E+04   0.229010 -0.004769
7.94E+04   0.228992 -0.006042
3.98E+05   0.228903 -0.010502
1.58E+04   0.228692  0.012738
1.26E+04   0.227200  0.016884
5.01E+05   0.226689 -0.015985
1.00E+04   0.225560  0.020809
7.94E+03   0.223945  0.024078
Param      0.078439 -0.010617
microg/ml  0.000515  0.998776

In [937]:
df_loadings.sort_values(by='PC2',ascending=False)

PC1       PC2
microg/ml  0.010839  0.997188
2.00E+04   0.348284  0.002988
2.51E+04   0.349705  0.002039
3.16E+04   0.350324  0.001191
3.98E+04   0.350376  0.000499
5.01E+04   0.350179 -0.000498
6.31E+04   0.349993 -0.001635
7.94E+04   0.349881 -0.001795
1.00E+05   0.349859 -0.002813
Param      0.144424 -0.074748