In [1]:
# 1. PCA dataset
import pandas as pd

df = pd.read_csv('../../mestrado/CalculosAnna/Eletrodo/baseHIVResParal.csv')
print(df)

# df['Sensor'] = df['Sensor'].astype('string')
df.head()

    Electrode  microg/ml     1.00E+06    7.94E+05    6.31E+05     5.01E+05  \
0         6.0      0.001  -59900000.0 -31700000.0 -12000000.0    1620000.0   
1         6.0      0.100  -59800000.0 -31400000.0 -11800000.0    1830000.0   
2         5.0      0.001 -108000000.0 -43500000.0  -8390000.0   10700000.0   
3         5.0      0.100 -110000000.0 -43600000.0  -8390000.0   10100000.0   
4         1.0      0.001   20100000.0  58600000.0  85500000.0  103000000.0   
5         1.0      0.010   14600000.0  53000000.0  79100000.0   96700000.0   
6         1.0      0.100   14300000.0  52600000.0  78700000.0   96800000.0   
7         1.0      1.000   19000000.0  58100000.0  85100000.0  103000000.0   
8         2.0      0.001   -8690000.0  26100000.0  50500000.0   67200000.0   
9         2.0      0.010  -12700000.0  21600000.0  45400000.0   61400000.0   
10        2.0      0.100  -13800000.0  20100000.0  44300000.0   60200000.0   
11        2.0      1.000  -12300000.0  22000000.0  45900000.0   

Electrode  microg/ml     1.00E+06    7.94E+05    6.31E+05     5.01E+05  \
0        6.0      0.001  -59900000.0 -31700000.0 -12000000.0    1620000.0   
1        6.0      0.100  -59800000.0 -31400000.0 -11800000.0    1830000.0   
2        5.0      0.001 -108000000.0 -43500000.0  -8390000.0   10700000.0   
3        5.0      0.100 -110000000.0 -43600000.0  -8390000.0   10100000.0   
4        1.0      0.001   20100000.0  58600000.0  85500000.0  103000000.0   

      3.98E+05     3.16E+05     2.51E+05     2.00E+05  ...    7.94E+00  \
0   11000000.0   17700000.0   22400000.0   26200000.0  ...  11100000.0   
1   11300000.0   17900000.0   22700000.0   26300000.0  ...  11400000.0   
2   21500000.0   26700000.0   30600000.0   32300000.0  ...  33800000.0   
3   20800000.0   26700000.0   30200000.0   32200000.0  ...  33700000.0   
4  116000000.0  123000000.0  127000000.0  128000000.0  ...  19700000.0   

     6.31E+00    5.01E+00    3.98E+00    3.16E+00    2.51E+00    2.00E+00  \
0  10300000.0   9540000.0   8850000.0   8230000.0   7700000.0   7250000.0   
1  10600000.0   9920000.0   9240000.0   8640000.0   8100000.0   7650000.0   
2  31600000.0  29400000.0  27200000.0  25300000.0  23400000.0  21500000.0   
3  31600000.0  29500000.0  27600000.0  25600000.0  23700000.0  21900000.0   
4  15100000.0  11400000.0   8370000.0   6030000.0   4250000.0   2930000.0   

     1.58E+00    1.26E+00    1.00E+00  
0   6880000.0   6620000.0   6430000.0  
1   7270000.0   6990000.0   6750000.0  
2  19700000.0  18200000.0  16600000.0  
3  20400000.0  18700000.0  17200000.0  
4   2010000.0   1370000.0    917000.0  

[5 rows x 63 columns]

In [2]:
print(df.dtypes)

Electrode    float64
microg/ml    float64
1.00E+06     float64
7.94E+05     float64
6.31E+05     float64
              ...   
2.51E+00     float64
2.00E+00     float64
1.58E+00     float64
1.26E+00     float64
1.00E+00     float64
Length: 63, dtype: object


In [3]:
df_features = df.iloc[:,1:].copy()
X = df_features.to_numpy()
# X = df.values
X

array([[ 1.00e-03, -5.99e+07, -3.17e+07, ...,  6.88e+06,  6.62e+06,
         6.43e+06],
       [ 1.00e-01, -5.98e+07, -3.14e+07, ...,  7.27e+06,  6.99e+06,
         6.75e+06],
       [ 1.00e-03, -1.08e+08, -4.35e+07, ...,  1.97e+07,  1.82e+07,
         1.66e+07],
       ...,
       [ 1.00e-02, -6.74e+06,  2.89e+07, ...,  1.44e+07,  1.45e+07,
         1.46e+07],
       [ 1.00e-01, -7.31e+06,  2.86e+07, ...,  1.39e+07,  1.39e+07,
         1.39e+07],
       [ 1.00e+00, -6.19e+06,  2.96e+07, ...,  1.28e+07,  1.29e+07,
         1.29e+07]])

In [4]:
Y = df.iloc[:, 0].to_numpy()
Y

array([6., 6., 5., 5., 1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4.,
       4., 4., 4.])

In [5]:
X.shape

(20, 62)

In [6]:
Y.shape

(20,)

In [7]:
# 2. PCA analysis
# 2.1 Load library

from sklearn.preprocessing import scale # Data scaling
from sklearn import decomposition # PCA
import pandas as pd # pandas

In [8]:
# 2.2 Data scaling
x = scale(X)

# Standardize the Data
# PCA is effected by scale so you need to scale the features in your data before applying PCA. Use StandardScaler to help you standardize the dataset’s features onto unit scale (mean = 0 and variance = 1) which is a requirement for the optimal performance of many machine learning algorithms.
x

array([[-0.59910015, -1.14344786, -1.66825143, ..., -0.54777877,
        -0.54426016, -0.54054811],
       [-0.34267596, -1.14068447, -1.65863153, ..., -0.54075112,
        -0.53733443, -0.53412594],
       [-0.59910015, -2.47263673, -2.04663427, ..., -0.3167671 ,
        -0.32750324, -0.33644349],
       ...,
       [-0.57578886,  0.32556837,  0.27496888, ..., -0.41227114,
        -0.39676063, -0.37658205],
       [-0.34267596,  0.30981707,  0.26534898, ..., -0.42128096,
        -0.40799156, -0.39063055],
       [ 1.98845304,  0.340767  ,  0.29741532, ..., -0.44110255,
        -0.42670978, -0.41069984]])

In [9]:
# 2.3 Perform PCA analysis
pca = decomposition.PCA(n_components=2)
pca.fit(x) # when build the model we use pca.fit function. Where by the argument will be the input data, which essencially is the x variable
# we are using the x variable because pca is an unsupervised learning approach, meaning that it does not need the y variable or the class label in order to learn
# it`ll goind to cluster the data based on similarity and differences, based on the eigenvalue that are inherently present in the data set

PCA(n_components=2)

In [10]:
# 2.4 compure the scores value
# scores value will essentially be represented by the data samples so we`re gonna use the pca.transform function
scores = pca.transform(x)

In [11]:
scores

array([[-7.92575174, -3.14714636],
       [-7.9028553 , -3.14158752],
       [-7.62377478, -4.37202192],
       [-7.64780721, -4.38383688],
       [ 3.52447261,  5.2630136 ],
       [ 2.71414825,  4.73240937],
       [ 2.77993739,  4.80683555],
       [ 3.74838191,  5.60857509],
       [-4.15193877,  0.63575773],
       [-4.47643098,  0.34622638],
       [-4.44783104,  0.35204003],
       [-4.0862066 ,  0.71650362],
       [10.29980579, -3.88655102],
       [11.57110661, -3.69567682],
       [12.36854843, -3.24954761],
       [13.03319051, -2.54963245],
       [-2.96286811,  1.41870413],
       [-3.0055252 ,  1.39835138],
       [-3.02439032,  1.4155922 ],
       [-2.78421148,  1.7319915 ]])

In [12]:
scores_df = pd.DataFrame(scores, columns=['PC1', 'PC2']) # dataframe is to make more readable
scores_df

PC1       PC2
0   -7.925752 -3.147146
1   -7.902855 -3.141588
2   -7.623775 -4.372022
3   -7.647807 -4.383837
4    3.524473  5.263014
5    2.714148  4.732409
6    2.779937  4.806836
7    3.748382  5.608575
8   -4.151939  0.635758
9   -4.476431  0.346226
10  -4.447831  0.352040
11  -4.086207  0.716504
12  10.299806 -3.886551
13  11.571107 -3.695677
14  12.368548 -3.249548
15  13.033191 -2.549632
16  -2.962868  1.418704
17  -3.005525  1.398351
18  -3.024390  1.415592
19  -2.784211  1.731991

In [34]:
y_label = []

for i in Y:
    if i == 1:
        y_label.append('Electrode 1')
    elif i == 2:
        y_label.append('Electrode 2')
    elif i == 3:
        y_label.append('Electrode 3')
    elif i == 4:
        y_label.append('Electrode 4')
    elif i == 5:
        y_label.append('Lignin')
    else:
        y_label.append('AntiHCV Electrode 1')

sensors = pd.DataFrame(y_label, columns=['Sensor'])

In [35]:
df_scores = pd.concat([scores_df, sensors], axis=1) # combine dataframes with concat
df_scores

PC1       PC2               Sensor
0   -7.925752 -3.147146  AntiHCV Electrode 1
1   -7.902855 -3.141588  AntiHCV Electrode 1
2   -7.623775 -4.372022               Lignin
3   -7.647807 -4.383837               Lignin
4    3.524473  5.263014          Electrode 1
5    2.714148  4.732409          Electrode 1
6    2.779937  4.806836          Electrode 1
7    3.748382  5.608575          Electrode 1
8   -4.151939  0.635758          Electrode 2
9   -4.476431  0.346226          Electrode 2
10  -4.447831  0.352040          Electrode 2
11  -4.086207  0.716504          Electrode 2
12  10.299806 -3.886551          Electrode 3
13  11.571107 -3.695677          Electrode 3
14  12.368548 -3.249548          Electrode 3
15  13.033191 -2.549632          Electrode 3
16  -2.962868  1.418704          Electrode 4
17  -3.005525  1.398351          Electrode 4
18  -3.024390  1.415592          Electrode 4
19  -2.784211  1.731991          Electrode 4

In [36]:
feature_names = df.columns[1:]
feature_names

Index(['microg/ml', '1.00E+06', '7.94E+05', '6.31E+05', '5.01E+05', '3.98E+05',
       '3.16E+05', '2.51E+05', '2.00E+05', '1.58E+05', '1.26E+05', '1.00E+05',
       '7.94E+04', '6.31E+04', '5.01E+04', '3.98E+04', '3.16E+04', '2.51E+04',
       '2.00E+04', '1.58E+04', '1.26E+04', '1.00E+04', '7.94E+03', '6.31E+03',
       '5.01E+03', '3.98E+03', '3.16E+03', '2.51E+03', '2.00E+03', '1.58E+03',
       '1.26E+03', '1.00E+03', '7.94E+02', '6.31E+02', '5.01E+02', '3.98E+02',
       '3.16E+02', '2.51E+02', '2.00E+02', '1.58E+02', '1.26E+02', '1.00E+02',
       '7.94E+01', '6.31E+01', '5.01E+01', '3.98E+01', '3.16E+01', '2.51E+01',
       '2.00E+01', '1.58E+01', '1.26E+01', '1.00E+01', '7.94E+00', '6.31E+00',
       '5.01E+00', '3.98E+00', '3.16E+00', '2.51E+00', '2.00E+00', '1.58E+00',
       '1.26E+00', '1.00E+00'],
      dtype='object')

In [37]:
# 2.5 retrieve the loading values (remember PCA scores and loadings)
# loadings value tell about the descriptor and scores value tell about the data samples
# 150 flowers 150 score values 4 descriptors 4 loading values (1 for each descriptor)
loadings = pca.components_.T
df_loadings = pd.DataFrame(loadings, columns=['PC1', 'PC2'], index=feature_names)
df_loadings

PC1       PC2
microg/ml  0.024913  0.060527
1.00E+06   0.081202  0.216041
7.94E+05   0.089636  0.222032
6.31E+05   0.098270  0.206807
5.01E+05   0.106858  0.185007
...             ...       ...
2.51E+00   0.119225 -0.167895
2.00E+00   0.118833 -0.168559
1.58E+00   0.118408 -0.169326
1.26E+00   0.118513 -0.168466
1.00E+00   0.117956 -0.168960

[62 rows x 2 columns]

In [38]:
# 2.6 explained variance
# what`s the contribuition to the percent variance of the entire model contributed by each of the principal components
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.76995153, 0.17638723])

In [39]:
# 3. Scree plot
import numpy as np
import plotly.express as px

In [40]:
# 3.1 preparing the explained variance data
# add origin value, x and y are going to have origin zero, the subsequent lines of code are going to create the scree plot
# the scree plot does not start from zero, then we need to manually create the zero origin
explained_variance = np.insert(explained_variance, 0, 0)
explained_variance

array([0.        , 0.76995153, 0.17638723])

In [41]:
# 3.2 Preparing cumulative variance data
cumulative_variance = np.cumsum(np.round(explained_variance, decimals=3))

In [42]:
# 3.3 Combining dataframe
pc_df = pd.DataFrame(['', 'PC1', 'PC2'], columns=['PC'])
explained_variance_df = pd.DataFrame(explained_variance, columns=['Explained Variance'])
cumulative_variance_df = pd.DataFrame(cumulative_variance, columns=['Cumulative Variance'])

In [43]:
df_explained_variance = pd.concat([pc_df, explained_variance_df, cumulative_variance_df], axis=1)
df_explained_variance

PC  Explained Variance  Cumulative Variance
0                 0.000000                0.000
1  PC1            0.769952                0.770
2  PC2            0.176387                0.946

In [44]:
# 3.4 Creating Scree Plot
# https://plotly.com/python/bar-charts/

fig = px.bar(df_explained_variance, x='PC', y='Explained Variance', text='Explained Variance', width=800)

In [45]:
fig.update_traces(texttemplate='%{text:.3f}', textposition='outside') # limit decimal cases and text outside the bar
fig.show() #explained variance

In [46]:
# explained variance + cumulative variance
# https://plotly.com/python/creating-and-updating-figures

import plotly.graph_objects as go
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ))

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ))

fig.show()

In [47]:
# Explained variance + cumulative variance (Separate Plot)

from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=1, cols=2)

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ), row=1, col=1
)

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ), row=1, col=2
)

fig.show()

In [48]:
# 4. Scores plot
# check API documentation for plotly.express https://plotly.com/python/3d-scatter-plots

import plotly.express as px

fig = px.scatter(df_scores, x='PC1', y='PC2', color='Sensor')
fig.show()

In [28]:
# 4.1 Customize 3D Scatter Plot

fig = px.scatter(df_scores, x='PC1', y='PC2', color='Sensor', symbol='Sensor', opacity=0.4)

# tight layout
fig.update_layout(margin=dict(l=0, r=0, b=0, t=0)) # left, right, bottom, top with zero margin

fig.show()

# https://plotly.com/python/templates/
# fig.update_layout(template='plotly_white')
# plotly, plotly_white, plotly_dark, ggplot2, seaborn, simple_white, none

In [29]:
# 5. Loadings Plot

loadings_label = df_loadings.index
# loadings_label = df_loadings.index.str.strip(' (cm)')

fig = px.scatter(df_loadings, x='PC1', y='PC2', text=loadings_label)
fig.show()

In [30]:
loadings_label

Index(['microg/ml', '1.00E+06', '7.94E+05', '6.31E+05', '5.01E+05', '3.98E+05',
       '3.16E+05', '2.51E+05', '2.00E+05', '1.58E+05', '1.26E+05', '1.00E+05',
       '7.94E+04', '6.31E+04', '5.01E+04', '3.98E+04', '3.16E+04', '2.51E+04',
       '2.00E+04', '1.58E+04', '1.26E+04', '1.00E+04', '7.94E+03', '6.31E+03',
       '5.01E+03', '3.98E+03', '3.16E+03', '2.51E+03', '2.00E+03', '1.58E+03',
       '1.26E+03', '1.00E+03', '7.94E+02', '6.31E+02', '5.01E+02', '3.98E+02',
       '3.16E+02', '2.51E+02', '2.00E+02', '1.58E+02', '1.26E+02', '1.00E+02',
       '7.94E+01', '6.31E+01', '5.01E+01', '3.98E+01', '3.16E+01', '2.51E+01',
       '2.00E+01', '1.58E+01', '1.26E+01', '1.00E+01', '7.94E+00', '6.31E+00',
       '5.01E+00', '3.98E+00', '3.16E+00', '2.51E+00', '2.00E+00', '1.58E+00',
       '1.26E+00', '1.00E+00'],
      dtype='object')

In [31]:
df_loadings

PC1       PC2
microg/ml  0.024913  0.060527
1.00E+06   0.081202  0.216041
7.94E+05   0.089636  0.222032
6.31E+05   0.098270  0.206807
5.01E+05   0.106858  0.185007
...             ...       ...
2.51E+00   0.119225 -0.167895
2.00E+00   0.118833 -0.168559
1.58E+00   0.118408 -0.169326
1.26E+00   0.118513 -0.168466
1.00E+00   0.117956 -0.168960

[62 rows x 2 columns]

In [32]:
df_loadings.sort_values(by='PC1',ascending=False)

PC1       PC2
5.01E+02   0.141934 -0.015567
3.98E+02   0.141850 -0.028012
6.31E+02   0.141576  0.001089
3.16E+02   0.141450 -0.043170
2.51E+02   0.140748 -0.056870
...             ...       ...
5.01E+05   0.106858  0.185007
6.31E+05   0.098270  0.206807
7.94E+05   0.089636  0.222032
1.00E+06   0.081202  0.216041
microg/ml  0.024913  0.060527

[62 rows x 2 columns]

In [33]:
df_loadings.sort_values(by='PC2',ascending=False)

PC1       PC2
7.94E+05  0.089636  0.222032
1.00E+06  0.081202  0.216041
6.31E+05  0.098270  0.206807
5.01E+05  0.106858  0.185007
1.00E+04  0.118781  0.164155
...            ...       ...
2.51E+00  0.119225 -0.167895
1.26E+00  0.118513 -0.168466
2.00E+00  0.118833 -0.168559
1.00E+00  0.117956 -0.168960
1.58E+00  0.118408 -0.169326

[62 rows x 2 columns]