In [110]:
# 1. PCA dataset
import pandas as pd

df = pd.read_csv('../../mestrado/CalculosAnna/SensorAltaConc/baseAllSensorsHigh.csv')
print(df)

# df['Sensor'] = df['Sensor'].astype('string')
df.head()

    Sensor  Electrode  Param  microg/ml      1.00E+06      7.94E+05  \
0      1.0        6.0    1.0        0.1  7.250000e+01  7.270000e+01   
1      1.0        1.0    1.0        0.1  1.100000e+02  1.120000e+02   
2      1.0        1.0    1.0        1.0  1.110000e+02  1.120000e+02   
3      1.0        2.0    1.0        0.1  6.960000e+01  7.080000e+01   
4      1.0        2.0    1.0        1.0  7.040000e+01  7.150000e+01   
..     ...        ...    ...        ...           ...           ...   
85     2.0        1.0    6.0        0.2 -9.150000e-09 -2.400000e-08   
86     2.0        1.0    6.0        1.0 -9.080000e-09 -2.370000e-08   
87     2.0        2.0    6.0        0.1 -9.130000e-08  3.850000e-08   
88     2.0        2.0    6.0        0.2 -1.550000e-07  3.270000e-08   
89     2.0        2.0    6.0        1.0 -2.390000e-07  3.020000e-08   

        6.31E+05      5.01E+05      3.98E+05      3.16E+05  ...      7.94E+00  \
0   7.280000e+01  7.300000e+01  7.330000e+01  7.370000e+01  ...  1

Sensor  Electrode  Param  microg/ml  1.00E+06  7.94E+05  6.31E+05  \
0     1.0        6.0    1.0        0.1      72.5      72.7      72.8   
1     1.0        1.0    1.0        0.1     110.0     112.0     113.0   
2     1.0        1.0    1.0        1.0     111.0     112.0     114.0   
3     1.0        2.0    1.0        0.1      69.6      70.8      72.3   
4     1.0        2.0    1.0        1.0      70.4      71.5      73.0   

   5.01E+05  3.98E+05  3.16E+05  ...  7.94E+00  6.31E+00  5.01E+00  3.98E+00  \
0      73.0      73.3      73.7  ...   16800.0   20700.0   25500.0   31200.0   
1     116.0     119.0     122.0  ...  170000.0  206000.0  244000.0  283000.0   
2     116.0     119.0     122.0  ...  179000.0  217000.0  256000.0  295000.0   
3      74.2      76.6      79.6  ...   30400.0   37600.0   46200.0   56400.0   
4      74.9      77.3      80.3  ...   31300.0   38800.0   47800.0   58900.0   

   3.16E+00  2.51E+00  2.00E+00  1.58E+00  1.26E+00  1.00E+00  
0   37800.0   45700.0   54600.0   64800.0   76200.0   89100.0  
1  320000.0  355000.0  386000.0  413000.0  435000.0  454000.0  
2  333000.0  367000.0  398000.0  424000.0  446000.0  464000.0  
3   68600.0   82900.0   99600.0  119000.0  141000.0  168000.0  
4   71900.0   87100.0  105000.0  126000.0  150000.0  177000.0  

[5 rows x 65 columns]

In [111]:
print(df.dtypes)

Sensor       float64
Electrode    float64
Param        float64
microg/ml    float64
1.00E+06     float64
              ...   
2.51E+00     float64
2.00E+00     float64
1.58E+00     float64
1.26E+00     float64
1.00E+00     float64
Length: 65, dtype: object


In [112]:
df_features = df.iloc[:,1:].copy()
X = df_features.to_numpy()
# X = df.values
X

array([[6.00e+00, 1.00e+00, 1.00e-01, ..., 6.48e+04, 7.62e+04, 8.91e+04],
       [1.00e+00, 1.00e+00, 1.00e-01, ..., 4.13e+05, 4.35e+05, 4.54e+05],
       [1.00e+00, 1.00e+00, 1.00e+00, ..., 4.24e+05, 4.46e+05, 4.64e+05],
       ...,
       [2.00e+00, 6.00e+00, 1.00e-01, ..., 3.67e-08, 4.01e-08, 4.49e-08],
       [2.00e+00, 6.00e+00, 2.00e-01, ..., 3.65e-08, 4.04e-08, 4.50e-08],
       [2.00e+00, 6.00e+00, 1.00e+00, ..., 3.50e-08, 3.87e-08, 4.24e-08]])

In [113]:
Y = df.iloc[:, 0].to_numpy()
Y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2.])

In [114]:
X.shape

(90, 64)

In [115]:
Y.shape

(90,)

In [116]:
# 2. PCA analysis
# 2.1 Load library

from sklearn.preprocessing import scale # Data scaling
from sklearn import decomposition # PCA
import pandas as pd # pandas

In [117]:
# 2.2 Data scaling
x = scale(X)

# Standardize the Data
# PCA is effected by scale so you need to scale the features in your data before applying PCA. Use StandardScaler to help you standardize the dataset’s features onto unit scale (mean = 0 and variance = 1) which is a requirement for the optimal performance of many machine learning algorithms.
x

array([[ 2.62202212, -1.46385011, -0.86574938, ..., -0.2852482 ,
        -0.28096815, -0.27953782],
       [-0.95346259, -1.46385011, -0.86574938, ..., -0.27272598,
        -0.26766003, -0.2650639 ],
       [-0.95346259, -1.46385011,  1.22132502, ..., -0.27233039,
        -0.26725203, -0.26466725],
       ...,
       [-0.23836565,  1.46385011, -0.86574938, ..., -0.28757859,
        -0.28379446, -0.28307201],
       [-0.23836565,  1.46385011, -0.63385222, ..., -0.28757859,
        -0.28379446, -0.28307201],
       [-0.23836565,  1.46385011,  1.22132502, ..., -0.28757859,
        -0.28379446, -0.28307201]])

In [118]:
# 2.3 Perform PCA analysis
pca = decomposition.PCA(n_components=3)
pca.fit(x) # when build the model we use pca.fit function. Where by the argument will be the input data, which essencially is the x variable
# we are using the x variable because pca is an unsupervised learning approach, meaning that it does not need the y variable or the class label in order to learn
# it`ll goind to cluster the data based on similarity and differences, based on the eigenvalue that are inherently present in the data set

PCA(n_components=3)

In [119]:
# 2.4 compure the scores value
# scores value will essentially be represented by the data samples so we`re gonna use the pca.transform function
scores = pca.transform(x)

In [120]:
scores

array([[-2.89156381e+00, -3.18166536e-01,  1.91786502e+00],
       [-2.84697967e+00, -3.64885442e-01, -6.22910749e-01],
       [-2.83848449e+00, -3.28336798e-01, -1.72194346e+00],
       [-2.86423257e+00, -3.44261237e-01, -1.15855005e-01],
       [-2.85608113e+00, -3.07277550e-01, -1.21491209e+00],
       [-2.86598572e+00, -3.44965131e-01,  3.93507892e-01],
       [-2.85737799e+00, -3.08627365e-01, -7.05466270e-01],
       [-2.87815206e+00, -3.30760978e-01,  9.00909115e-01],
       [-2.87001702e+00, -2.93747733e-01, -1.98156135e-01],
       [-2.87167851e+00, -2.86134902e-01,  2.05876552e+00],
       [-2.84303375e+00, -3.12559026e-01, -4.83372245e-01],
       [-2.83526096e+00, -2.75129157e-01, -1.58244590e+00],
       [-2.84903015e+00, -3.05927621e-01,  2.43996192e-02],
       [-2.84141678e+00, -2.68214512e-01, -1.07473440e+00],
       [-2.90709270e+00, -2.28077819e-01,  5.24467836e-01],
       [-2.90067744e+00, -1.88725553e-01, -5.74841154e-01],
       [-2.86218230e+00, -2.93511925e-01

In [121]:
scores_df = pd.DataFrame(scores, columns=['PC1', 'PC2', 'PC3']) # dataframe is to make more readable
scores_df

PC1       PC2       PC3
0  -2.891564 -0.318167  1.917865
1  -2.846980 -0.364885 -0.622911
2  -2.838484 -0.328337 -1.721943
3  -2.864233 -0.344261 -0.115855
4  -2.856081 -0.307278 -1.214912
..       ...       ...       ...
85 -2.719401 -0.237957 -0.036304
86 -2.712335 -0.204835 -1.013272
87 -2.726671 -0.236181  0.594313
88 -2.725787 -0.232041  0.472192
89 -2.718721 -0.198919 -0.504776

[90 rows x 3 columns]

In [122]:
y_label = []

for i in Y:
    if i == 1:
        y_label.append('HCV')
    else:
        y_label.append('HIV')

sensors = pd.DataFrame(y_label, columns=['Sensor'])

In [123]:
df_scores = pd.concat([scores_df, sensors], axis=1) # combine dataframes with concat
df_scores

PC1       PC2       PC3 Sensor
0  -2.891564 -0.318167  1.917865    HCV
1  -2.846980 -0.364885 -0.622911    HCV
2  -2.838484 -0.328337 -1.721943    HCV
3  -2.864233 -0.344261 -0.115855    HCV
4  -2.856081 -0.307278 -1.214912    HCV
..       ...       ...       ...    ...
85 -2.719401 -0.237957 -0.036304    HIV
86 -2.712335 -0.204835 -1.013272    HIV
87 -2.726671 -0.236181  0.594313    HIV
88 -2.725787 -0.232041  0.472192    HIV
89 -2.718721 -0.198919 -0.504776    HIV

[90 rows x 4 columns]

In [124]:
feature_names = df.columns[1:]
feature_names

Index(['Electrode', 'Param', 'microg/ml', '1.00E+06', '7.94E+05', '6.31E+05',
       '5.01E+05', '3.98E+05', '3.16E+05', '2.51E+05', '2.00E+05', '1.58E+05',
       '1.26E+05', '1.00E+05', '7.94E+04', '6.31E+04', '5.01E+04', '3.98E+04',
       '3.16E+04', '2.51E+04', '2.00E+04', '1.58E+04', '1.26E+04', '1.00E+04',
       '7.94E+03', '6.31E+03', '5.01E+03', '3.98E+03', '3.16E+03', '2.51E+03',
       '2.00E+03', '1.58E+03', '1.26E+03', '1.00E+03', '7.94E+02', '6.31E+02',
       '5.01E+02', '3.98E+02', '3.16E+02', '2.51E+02', '2.00E+02', '1.58E+02',
       '1.26E+02', '1.00E+02', '7.94E+01', '6.31E+01', '5.01E+01', '3.98E+01',
       '3.16E+01', '2.51E+01', '2.00E+01', '1.58E+01', '1.26E+01', '1.00E+01',
       '7.94E+00', '6.31E+00', '5.01E+00', '3.98E+00', '3.16E+00', '2.51E+00',
       '2.00E+00', '1.58E+00', '1.26E+00', '1.00E+00'],
      dtype='object')

In [125]:
# 2.5 retrieve the loading values (remember PCA scores and loadings)
# loadings value tell about the descriptor and scores value tell about the data samples
# 150 flowers 150 score values 4 descriptors 4 loading values (1 for each descriptor)
loadings = pca.components_.T
df_loadings = pd.DataFrame(loadings, columns=['PC1', 'PC2', 'PC3'], index=feature_names)
df_loadings

PC1       PC2       PC3
Electrode -0.008931  0.008273  0.711087
Param      0.048313  0.035108  0.242768
microg/ml  0.003809  0.017854 -0.526617
1.00E+06  -0.058718  0.208162 -0.152794
7.94E+05   0.054081  0.289543 -0.079653
...             ...       ...       ...
2.51E+00   0.122015 -0.169934  0.017288
2.00E+00   0.121451 -0.172193  0.020825
1.58E+00   0.121032 -0.173920  0.023180
1.26E+00   0.120610 -0.174822  0.023585
1.00E+00   0.119868 -0.178549  0.030262

[64 rows x 3 columns]

In [126]:
# 2.6 explained variance
# what`s the contribuition to the percent variance of the entire model contributed by each of the principal components
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.81149453, 0.11824357, 0.01835534])

In [127]:
# 3. Scree plot
import numpy as np
import plotly.express as px

In [128]:
# 3.1 preparing the explained variance data
# add origin value, x and y are going to have origin zero, the subsequent lines of code are going to create the scree plot
# the scree plot does not start from zero, then we need to manually create the zero origin
explained_variance = np.insert(explained_variance, 0, 0)
explained_variance

array([0.        , 0.81149453, 0.11824357, 0.01835534])

In [129]:
# 3.2 Preparing cumulative variance data
cumulative_variance = np.cumsum(np.round(explained_variance, decimals=3))

In [130]:
# 3.3 Combining dataframe
pc_df = pd.DataFrame(['', 'PC1', 'PC2', 'PC3'], columns=['PC'])
explained_variance_df = pd.DataFrame(explained_variance, columns=['Explained Variance'])
cumulative_variance_df = pd.DataFrame(cumulative_variance, columns=['Cumulative Variance'])

In [131]:
df_explained_variance = pd.concat([pc_df, explained_variance_df, cumulative_variance_df], axis=1)
df_explained_variance

PC  Explained Variance  Cumulative Variance
0                 0.000000                0.000
1  PC1            0.811495                0.811
2  PC2            0.118244                0.929
3  PC3            0.018355                0.947

In [132]:
# 3.4 Creating Scree Plot
# https://plotly.com/python/bar-charts/

fig = px.bar(df_explained_variance, x='PC', y='Explained Variance', text='Explained Variance', width=800)

In [133]:
fig.update_traces(texttemplate='%{text:.3f}', textposition='outside') # limit decimal cases and text outside the bar
fig.show() #explained variance

In [134]:
# explained variance + cumulative variance
# https://plotly.com/python/creating-and-updating-figures

import plotly.graph_objects as go
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ))

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ))

fig.show()

In [135]:
# Explained variance + cumulative variance (Separate Plot)

from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=1, cols=2)

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ), row=1, col=1
)

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ), row=1, col=2
)

fig.show()

In [136]:
# 4. Scores plot
# check API documentation for plotly.express https://plotly.com/python/3d-scatter-plots

import plotly.express as px

fig = px.scatter_3d(df_scores, x='PC1', y='PC2', z='PC3', color='Sensor')
fig.show()

In [109]:
# 4.1 Customize 3D Scatter Plot

fig = px.scatter_3d(df_scores, x='PC1', y='PC2', z='PC3', color='Sensor', symbol='Sensor', opacity=0.5)

# tight layout
fig.update_layout(margin=dict(l=0, r=0, b=0, t=0)) # left, right, bottom, top with zero margin

fig.show()

# https://plotly.com/python/templates/
# fig.update_layout(template='plotly_white')
# plotly, plotly_white, plotly_dark, ggplot2, seaborn, simple_white, none

In [61]:
# 5. Loadings Plot

loadings_label = df_loadings.index
# loadings_label = df_loadings.index.str.strip(' (cm)')

fig = px.scatter_3d(df_loadings, x='PC1', y='PC2', z='PC3', text=loadings_label)
fig.show()

In [62]:
loadings_label

Index(['Electrode', 'Param', 'microg/ml', '1.00E+06', '7.94E+05', '6.31E+05',
       '5.01E+05', '3.98E+05', '3.16E+05', '2.51E+05', '2.00E+05', '1.58E+05',
       '1.26E+05', '1.00E+05', '7.94E+04', '6.31E+04', '5.01E+04', '3.98E+04',
       '3.16E+04', '2.51E+04', '2.00E+04', '1.58E+04', '1.26E+04', '1.00E+04',
       '7.94E+03', '6.31E+03', '5.01E+03', '3.98E+03', '3.16E+03', '2.51E+03',
       '2.00E+03', '1.58E+03', '1.26E+03', '1.00E+03', '7.94E+02', '6.31E+02',
       '5.01E+02', '3.98E+02', '3.16E+02', '2.51E+02', '2.00E+02', '1.58E+02',
       '1.26E+02', '1.00E+02', '7.94E+01', '6.31E+01', '5.01E+01', '3.98E+01',
       '3.16E+01', '2.51E+01', '2.00E+01', '1.58E+01', '1.26E+01', '1.00E+01',
       '7.94E+00', '6.31E+00', '5.01E+00', '3.98E+00', '3.16E+00', '2.51E+00',
       '2.00E+00', '1.58E+00', '1.26E+00', '1.00E+00'],
      dtype='object')

In [63]:
df_loadings

PC1       PC2       PC3
Electrode -0.008735  0.006642  0.712155
Param      0.048564  0.033353  0.266288
microg/ml  0.003358  0.012335 -0.388777
1.00E+06  -0.058460  0.202729 -0.133312
7.94E+05   0.053821  0.283642 -0.049458
...             ...       ...       ...
2.51E+00   0.121693 -0.171376  0.031497
2.00E+00   0.121133 -0.173680  0.035303
1.58E+00   0.120680 -0.175219  0.039585
1.26E+00   0.120262 -0.176519  0.041167
1.00E+00   0.119599 -0.178892  0.046675

[64 rows x 3 columns]

In [65]:
df_loadings.sort_values(by='PC1',ascending=False)

PC1       PC2       PC3
5.01E+02   0.137660 -0.007593 -0.076791
3.98E+02   0.137626 -0.022410 -0.070723
6.31E+02   0.137397  0.010305 -0.083341
3.16E+02   0.137264 -0.038246 -0.064506
7.94E+02   0.136763  0.028615 -0.089482
...             ...       ...       ...
7.94E+05   0.053821  0.283642 -0.049458
Param      0.048564  0.033353  0.266288
microg/ml  0.003358  0.012335 -0.388777
Electrode -0.008735  0.006642  0.712155
1.00E+06  -0.058460  0.202729 -0.133312

[64 rows x 3 columns]

In [66]:
df_loadings.sort_values(by='PC2',ascending=False)

PC1       PC2       PC3
7.94E+05  0.053821  0.283642 -0.049458
6.31E+05  0.109798  0.209635  0.040910
1.00E+06 -0.058460  0.202729 -0.133312
5.01E+05  0.121809  0.162580  0.074421
7.94E+03  0.126883  0.140092 -0.049485
...            ...       ...       ...
2.51E+00  0.121693 -0.171376  0.031497
2.00E+00  0.121133 -0.173680  0.035303
1.58E+00  0.120680 -0.175219  0.039585
1.26E+00  0.120262 -0.176519  0.041167
1.00E+00  0.119599 -0.178892  0.046675

[64 rows x 3 columns]

In [67]:
df_loadings.sort_values(by='PC3',ascending=False)

PC1       PC2       PC3
Electrode -0.008735  0.006642  0.712155
Param      0.048564  0.033353  0.266288
1.58E+05   0.131070  0.101832  0.102995
1.26E+05   0.131853  0.095410  0.102899
1.00E+05   0.132415  0.090624  0.102285
...             ...       ...       ...
1.26E+03   0.134494  0.064305 -0.098141
2.00E+03   0.131477  0.095652 -0.099855
1.58E+03   0.132997  0.080909 -0.100214
1.00E+06  -0.058460  0.202729 -0.133312
microg/ml  0.003358  0.012335 -0.388777

[64 rows x 3 columns]