In [37]:
# 1. PCA dataset
import pandas as pd

df = pd.read_csv('../../mestrado/CalculosArtigo/Eletrodo/HCV/baseSensorsHCV2.csv')
print(df)

# df['Sensor'] = df['Sensor'].astype('string')
df.head()

    Electrode  microg/ml  1.00E+06  7.94E+05  6.31E+05  5.01E+05  3.98E+05  \
0         1.0      0.002     406.0     408.0     410.0     412.0     414.0   
1         1.0      0.010     406.0     408.0     410.0     412.0     414.0   
2         1.0      0.020     406.0     409.0     410.0     412.0     414.0   
3         1.0      0.100     407.0     409.0     411.0     413.0     415.0   
4         1.0      0.200     408.0     410.0     412.0     414.0     416.0   
5         1.0      1.000     409.0     411.0     413.0     415.0     417.0   
6         1.0      0.000     412.0     414.0     416.0     417.0     419.0   
7         2.0      0.002      75.7      76.4      77.4      78.8      80.7   
8         2.0      0.010      75.7      76.5      77.5      78.9      80.9   
9         2.0      0.020      75.8      76.6      77.6      79.0      80.9   
10        2.0      0.100      75.8      76.6      77.7      79.1      81.1   
11        2.0      0.200      76.3      77.1      78.1      79.6

Electrode  microg/ml  1.00E+06  7.94E+05  6.31E+05  5.01E+05  3.98E+05  \
0        1.0      0.002     406.0     408.0     410.0     412.0     414.0   
1        1.0      0.010     406.0     408.0     410.0     412.0     414.0   
2        1.0      0.020     406.0     409.0     410.0     412.0     414.0   
3        1.0      0.100     407.0     409.0     411.0     413.0     415.0   
4        1.0      0.200     408.0     410.0     412.0     414.0     416.0   

   3.16E+05  2.51E+05  2.00E+05  ...  7.94E+00  6.31E+00  5.01E+00  3.98E+00  \
0     417.0     420.0     424.0  ...   39100.0   49500.0   63400.0   80700.0   
1     416.0     419.0     423.0  ...   39400.0   50000.0   64100.0   81200.0   
2     417.0     420.0     423.0  ...   42900.0   53800.0   70100.0   89400.0   
3     417.0     420.0     424.0  ...   45600.0   57800.0   73800.0   94600.0   
4     418.0     421.0     424.0  ...   48400.0   61700.0   79100.0  100000.0   

   3.16E+00  2.51E+00  2.00E+00  1.58E+00  1.26E+00  1.00E+00  
0  102000.0  132000.0  164000.0  210000.0  258000.0  340000.0  
1  105000.0  130000.0  165000.0  215000.0  270000.0  340000.0  
2  116000.0  145000.0  183000.0  235000.0  295000.0  359000.0  
3  120000.0  153000.0  195000.0  249000.0  307000.0  405000.0  
4  126000.0  163000.0  206000.0  261000.0  331000.0  393000.0  

[5 rows x 63 columns]

In [38]:
print(df.dtypes)

Electrode    float64
microg/ml    float64
1.00E+06     float64
7.94E+05     float64
6.31E+05     float64
              ...   
2.51E+00     float64
2.00E+00     float64
1.58E+00     float64
1.26E+00     float64
1.00E+00     float64
Length: 63, dtype: object


In [39]:
df_features = df.iloc[:,1:].copy()
X = df_features.to_numpy()
# X = df.values
X

array([[2.00e-03, 4.06e+02, 4.08e+02, 4.10e+02, 4.12e+02, 4.14e+02,
        4.17e+02, 4.20e+02, 4.24e+02, 4.29e+02, 4.36e+02, 4.44e+02,
        4.53e+02, 4.64e+02, 4.77e+02, 4.91e+02, 5.04e+02, 5.18e+02,
        5.30e+02, 5.40e+02, 5.50e+02, 5.59e+02, 5.68e+02, 5.77e+02,
        5.88e+02, 6.01e+02, 6.16e+02, 6.37e+02, 6.61e+02, 6.93e+02,
        7.32e+02, 7.84e+02, 8.50e+02, 9.35e+02, 1.04e+03, 1.17e+03,
        1.35e+03, 1.54e+03, 1.81e+03, 2.17e+03, 2.61e+03, 3.17e+03,
        3.90e+03, 4.81e+03, 6.01e+03, 7.49e+03, 9.41e+03, 1.19e+04,
        1.50e+04, 1.89e+04, 2.41e+04, 3.06e+04, 3.91e+04, 4.95e+04,
        6.34e+04, 8.07e+04, 1.02e+05, 1.32e+05, 1.64e+05, 2.10e+05,
        2.58e+05, 3.40e+05],
       [1.00e-02, 4.06e+02, 4.08e+02, 4.10e+02, 4.12e+02, 4.14e+02,
        4.16e+02, 4.19e+02, 4.23e+02, 4.28e+02, 4.35e+02, 4.43e+02,
        4.53e+02, 4.64e+02, 4.77e+02, 4.92e+02, 5.07e+02, 5.23e+02,
        5.37e+02, 5.49e+02, 5.60e+02, 5.70e+02, 5.81e+02, 5.91e+02,
        6.02e+02, 6

In [40]:
Y = df.iloc[:, 0].to_numpy()
Y

array([1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 3., 3.])

In [41]:
X.shape

(16, 62)

In [42]:
Y.shape

(16,)

In [43]:
# 2. PCA analysis
# 2.1 Load library

from sklearn.preprocessing import scale # Data scaling
from sklearn import decomposition # PCA
import pandas as pd # pandas

In [44]:
# 2.2 Data scaling
x = scale(X)

# Standardize the Data
# PCA is effected by scale so you need to scale the features in your data before applying PCA. Use StandardScaler to help you standardize the dataset’s features onto unit scale (mean = 0 and variance = 1) which is a requirement for the optimal performance of many machine learning algorithms.
x

array([[-0.51159004,  1.12343082,  1.12261735,  1.12350654,  1.12438889,
         1.12437977,  1.12866803,  1.12861077,  1.13200597,  1.13363553,
         1.13786654,  1.14041271,  1.14022711,  1.14359038,  1.14521496,
         1.14143856,  1.1284002 ,  1.11824403,  1.10087399,  1.07965832,
         1.06502654,  1.0475046 ,  1.03147506,  1.01131465,  0.99231818,
         0.96438222,  0.92551537,  0.87371333,  0.77908323,  0.62174982,
         0.27450512, -0.49017932, -1.35318433, -1.52127469, -1.4968842 ,
        -1.46188996, -1.40943781, -1.38786939, -1.36937371, -1.34485246,
        -1.33341267, -1.32380497, -1.309728  , -1.30456106, -1.29449115,
        -1.29440493, -1.29087738, -1.29202152, -1.2954249 , -1.30636149,
        -1.31268252, -1.32787709, -1.33694295, -1.3567596 , -1.38584456,
        -1.41516129, -1.47161767, -1.44935334, -1.53496115, -1.59139992,
        -1.65336232, -1.5350712 ],
       [-0.48672917,  1.12343082,  1.12261735,  1.12350654,  1.12438889,
         1.12437

In [45]:
# 2.3 Perform PCA analysis
pca = decomposition.PCA(n_components=3)
pca.fit(x) # when build the model we use pca.fit function. Where by the argument will be the input data, which essencially is the x variable
# we are using the x variable because pca is an unsupervised learning approach, meaning that it does not need the y variable or the class label in order to learn
# it`ll goind to cluster the data based on similarity and differences, based on the eigenvalue that are inherently present in the data set

PCA(n_components=3)

In [46]:
# 2.4 compure the scores value
# scores value will essentially be represented by the data samples so we`re gonna use the pca.transform function
scores = pca.transform(x)

In [47]:
scores

array([[ 9.33955936, -1.96127008, -0.69108068],
       [ 9.38228624, -1.49997736, -0.65431581],
       [ 8.79859491, -0.70758767, -0.53023726],
       [ 8.38299134,  0.0279288 , -0.19166853],
       [ 8.00351862,  1.20246791,  0.05341524],
       [ 7.53134941,  2.11861408,  2.41348034],
       [ 6.20954702,  4.1067436 , -0.31444616],
       [-4.56736692, -3.30344493, -0.07638083],
       [-4.88165714, -3.0372525 , -0.13006564],
       [-4.99286313, -2.76592779, -0.16721591],
       [-5.28798091, -2.73003551,  0.01539656],
       [-6.20908787, -1.22878026,  0.36357188],
       [-7.28411092,  0.84616593,  2.61098178],
       [-8.38691965,  1.84471947, -0.19866942],
       [-8.04832237,  3.86971193, -1.53886807],
       [-7.98953798,  3.21792439, -0.9638975 ]])

In [48]:
scores_df = pd.DataFrame(scores, columns=['PC1', 'PC2', 'PC3']) # dataframe is to make more readable
scores_df

PC1       PC2       PC3
0   9.339559 -1.961270 -0.691081
1   9.382286 -1.499977 -0.654316
2   8.798595 -0.707588 -0.530237
3   8.382991  0.027929 -0.191669
4   8.003519  1.202468  0.053415
5   7.531349  2.118614  2.413480
6   6.209547  4.106744 -0.314446
7  -4.567367 -3.303445 -0.076381
8  -4.881657 -3.037253 -0.130066
9  -4.992863 -2.765928 -0.167216
10 -5.287981 -2.730036  0.015397
11 -6.209088 -1.228780  0.363572
12 -7.284111  0.846166  2.610982
13 -8.386920  1.844719 -0.198669
14 -8.048322  3.869712 -1.538868
15 -7.989538  3.217924 -0.963898

In [49]:
y_label = []

for i in Y:
    if i == 1:
        y_label.append('SF_NS5A_1bic')
    elif i == 2:
        y_label.append('SF_NS5A_5bic')
    else:
        y_label.append('SF_NS5A_5bicp24')

sensors = pd.DataFrame(y_label, columns=['Sensor'])

In [50]:
df_scores = pd.concat([scores_df, sensors], axis=1) # combine dataframes with concat
df_scores

PC1       PC2       PC3           Sensor
0   9.339559 -1.961270 -0.691081     SF_NS5A_1bic
1   9.382286 -1.499977 -0.654316     SF_NS5A_1bic
2   8.798595 -0.707588 -0.530237     SF_NS5A_1bic
3   8.382991  0.027929 -0.191669     SF_NS5A_1bic
4   8.003519  1.202468  0.053415     SF_NS5A_1bic
5   7.531349  2.118614  2.413480     SF_NS5A_1bic
6   6.209547  4.106744 -0.314446     SF_NS5A_1bic
7  -4.567367 -3.303445 -0.076381     SF_NS5A_5bic
8  -4.881657 -3.037253 -0.130066     SF_NS5A_5bic
9  -4.992863 -2.765928 -0.167216     SF_NS5A_5bic
10 -5.287981 -2.730036  0.015397     SF_NS5A_5bic
11 -6.209088 -1.228780  0.363572     SF_NS5A_5bic
12 -7.284111  0.846166  2.610982     SF_NS5A_5bic
13 -8.386920  1.844719 -0.198669     SF_NS5A_5bic
14 -8.048322  3.869712 -1.538868  SF_NS5A_5bicp24
15 -7.989538  3.217924 -0.963898  SF_NS5A_5bicp24

In [51]:
feature_names = df.columns[1:]
feature_names

Index(['microg/ml', '1.00E+06', '7.94E+05', '6.31E+05', '5.01E+05', '3.98E+05',
       '3.16E+05', '2.51E+05', '2.00E+05', '1.58E+05', '1.26E+05', '1.00E+05',
       '7.94E+04', '6.31E+04', '5.01E+04', '3.98E+04', '3.16E+04', '2.51E+04',
       '2.00E+04', '1.58E+04', '1.26E+04', '1.00E+04', '7.94E+03', '6.31E+03',
       '5.01E+03', '3.98E+03', '3.16E+03', '2.51E+03', '2.00E+03', '1.58E+03',
       '1.26E+03', '1.00E+03', '7.94E+02', '6.31E+02', '5.01E+02', '3.98E+02',
       '3.16E+02', '2.51E+02', '2.00E+02', '1.58E+02', '1.26E+02', '1.00E+02',
       '7.94E+01', '6.31E+01', '5.01E+01', '3.98E+01', '3.16E+01', '2.51E+01',
       '2.00E+01', '1.58E+01', '1.26E+01', '1.00E+01', '7.94E+00', '6.31E+00',
       '5.01E+00', '3.98E+00', '3.16E+00', '2.51E+00', '2.00E+00', '1.58E+00',
       '1.26E+00', '1.00E+00'],
      dtype='object')

In [52]:
# 2.5 retrieve the loading values (remember PCA scores and loadings)
# loadings value tell about the descriptor and scores value tell about the data samples
# 150 flowers 150 score values 4 descriptors 4 loading values (1 for each descriptor)
loadings = pca.components_.T
df_loadings = pd.DataFrame(loadings, columns=['PC1', 'PC2', 'PC3'], index=feature_names)
df_loadings

PC1       PC2       PC3
microg/ml  0.003678  0.083598  0.899877
1.00E+06   0.133448  0.069678  0.015257
7.94E+05   0.133439  0.069918  0.014538
6.31E+05   0.133415  0.070447  0.013893
5.01E+05   0.133401  0.070868  0.012897
...             ...       ...       ...
2.51E+00  -0.132534  0.061927  0.074178
2.00E+00  -0.131503  0.051243  0.118111
1.58E+00  -0.129324  0.039455  0.155875
1.26E+00  -0.126828  0.028570  0.206475
1.00E+00  -0.122832 -0.004756  0.256438

[62 rows x 3 columns]

In [53]:
# 2.6 explained variance
# what`s the contribuition to the percent variance of the entire model contributed by each of the principal components
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.87744255, 0.09636841, 0.0176283 ])

In [54]:
# 3. Scree plot
import numpy as np
import plotly.express as px

In [55]:
# 3.1 preparing the explained variance data
# add origin value, x and y are going to have origin zero, the subsequent lines of code are going to create the scree plot
# the scree plot does not start from zero, then we need to manually create the zero origin
explained_variance = np.insert(explained_variance, 0, 0)
explained_variance

array([0.        , 0.87744255, 0.09636841, 0.0176283 ])

In [56]:
# 3.2 Preparing cumulative variance data
cumulative_variance = np.cumsum(np.round(explained_variance, decimals=3))

In [57]:
# 3.3 Combining dataframe
pc_df = pd.DataFrame(['', 'PC1', 'PC2', 'PC3'], columns=['PC'])
explained_variance_df = pd.DataFrame(explained_variance, columns=['Explained Variance'])
cumulative_variance_df = pd.DataFrame(cumulative_variance, columns=['Cumulative Variance'])

In [58]:
df_explained_variance = pd.concat([pc_df, explained_variance_df, cumulative_variance_df], axis=1)
df_explained_variance

PC  Explained Variance  Cumulative Variance
0                 0.000000                0.000
1  PC1            0.877443                0.877
2  PC2            0.096368                0.973
3  PC3            0.017628                0.991

In [59]:
# 3.4 Creating Scree Plot
# https://plotly.com/python/bar-charts/

fig = px.bar(df_explained_variance, x='PC', y='Explained Variance', text='Explained Variance', width=800)

In [60]:
fig.update_traces(texttemplate='%{text:.3f}', textposition='outside') # limit decimal cases and text outside the bar
fig.show() #explained variance

In [61]:
# explained variance + cumulative variance
# https://plotly.com/python/creating-and-updating-figures

import plotly.graph_objects as go
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ))

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ))

fig.show()

In [62]:
# Explained variance + cumulative variance (Separate Plot)

from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=1, cols=2)

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ), row=1, col=1
)

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ), row=1, col=2
)

fig.show()

In [64]:
# 4. Scores plot
# check API documentation for plotly.express https://plotly.com/python/3d-scatter-plots

import plotly.express as px

fig = px.scatter_3d(df_scores, x='PC1', y='PC2', z='PC3', color='Sensor')
fig.show()

In [65]:
# 4.1 Customize 3D Scatter Plot

fig = px.scatter_3d(df_scores, x='PC1', y='PC2', z='PC3', color='Sensor', symbol='Sensor', opacity=0.4)

# tight layout
fig.update_layout(margin=dict(l=0, r=0, b=0, t=0)) # left, right, bottom, top with zero margin

fig.show()

# https://plotly.com/python/templates/
# fig.update_layout(template='plotly_white')
# plotly, plotly_white, plotly_dark, ggplot2, seaborn, simple_white, none

In [66]:
# 5. Loadings Plot

loadings_label = df_loadings.index
# loadings_label = df_loadings.index.str.strip(' (cm)')

fig = px.scatter_3d(df_loadings, x='PC1', y='PC2', z='PC3', text=loadings_label)
fig.show()

In [67]:
loadings_label

Index(['microg/ml', '1.00E+06', '7.94E+05', '6.31E+05', '5.01E+05', '3.98E+05',
       '3.16E+05', '2.51E+05', '2.00E+05', '1.58E+05', '1.26E+05', '1.00E+05',
       '7.94E+04', '6.31E+04', '5.01E+04', '3.98E+04', '3.16E+04', '2.51E+04',
       '2.00E+04', '1.58E+04', '1.26E+04', '1.00E+04', '7.94E+03', '6.31E+03',
       '5.01E+03', '3.98E+03', '3.16E+03', '2.51E+03', '2.00E+03', '1.58E+03',
       '1.26E+03', '1.00E+03', '7.94E+02', '6.31E+02', '5.01E+02', '3.98E+02',
       '3.16E+02', '2.51E+02', '2.00E+02', '1.58E+02', '1.26E+02', '1.00E+02',
       '7.94E+01', '6.31E+01', '5.01E+01', '3.98E+01', '3.16E+01', '2.51E+01',
       '2.00E+01', '1.58E+01', '1.26E+01', '1.00E+01', '7.94E+00', '6.31E+00',
       '5.01E+00', '3.98E+00', '3.16E+00', '2.51E+00', '2.00E+00', '1.58E+00',
       '1.26E+00', '1.00E+00'],
      dtype='object')

In [68]:
df_loadings

PC1       PC2       PC3
microg/ml  0.003678  0.083598  0.899877
1.00E+06   0.133448  0.069678  0.015257
7.94E+05   0.133439  0.069918  0.014538
6.31E+05   0.133415  0.070447  0.013893
5.01E+05   0.133401  0.070868  0.012897
...             ...       ...       ...
2.51E+00  -0.132534  0.061927  0.074178
2.00E+00  -0.131503  0.051243  0.118111
1.58E+00  -0.129324  0.039455  0.155875
1.26E+00  -0.126828  0.028570  0.206475
1.00E+00  -0.122832 -0.004756  0.256438

[62 rows x 3 columns]

In [69]:
df_loadings.sort_values(by='PC1',ascending=False)

PC1       PC2       PC3
1.00E+06  0.133448  0.069678  0.015257
7.94E+05  0.133439  0.069918  0.014538
6.31E+05  0.133415  0.070447  0.013893
5.01E+05  0.133401  0.070868  0.012897
3.98E+05  0.133365  0.071656  0.011576
...            ...       ...       ...
2.00E+00 -0.131503  0.051243  0.118111
5.01E+00 -0.131583  0.094920 -0.002538
3.98E+00 -0.132150  0.085432  0.015856
3.16E+00 -0.132459  0.076459  0.040147
2.51E+00 -0.132534  0.061927  0.074178

[62 rows x 3 columns]

In [70]:
df_loadings.sort_values(by='PC2',ascending=False)

PC1       PC2       PC3
1.00E+03  0.043395  0.385513 -0.000391
7.94E+02 -0.055911  0.369665 -0.027166
1.26E+03  0.099277  0.277121 -0.010560
6.31E+02 -0.106460  0.250849 -0.027023
1.58E+03  0.117084  0.205469 -0.004061
...            ...       ...       ...
2.51E+00 -0.132534  0.061927  0.074178
2.00E+00 -0.131503  0.051243  0.118111
1.58E+00 -0.129324  0.039455  0.155875
1.26E+00 -0.126828  0.028570  0.206475
1.00E+00 -0.122832 -0.004756  0.256438

[62 rows x 3 columns]

In [71]:
df_loadings.sort_values(by='PC3',ascending=False)

PC1       PC2       PC3
microg/ml  0.003678  0.083598  0.899877
1.00E+00  -0.122832 -0.004756  0.256438
1.26E+00  -0.126828  0.028570  0.206475
1.58E+00  -0.129324  0.039455  0.155875
2.00E+00  -0.131503  0.051243  0.118111
...             ...       ...       ...
5.01E+01  -0.129990  0.109824 -0.053407
2.00E+01  -0.129532  0.114034 -0.053627
3.98E+01  -0.129806  0.111503 -0.053684
2.51E+01  -0.129568  0.113599 -0.055394
3.16E+01  -0.129652  0.112370 -0.056482

[62 rows x 3 columns]