In [35]:
# 1. PCA dataset
import pandas as pd

df = pd.read_csv('../../mestrado/CalculosArtigo/Sensor/baseAllSensors782.csv')
print(df)

# df['Sensor'] = df['Sensor'].astype('string')
df.head()

    Sensor  Electrode  microg/ml  1.00E+06  7.94E+05  6.31E+05  5.01E+05  \
0      1.0        6.0      0.001      72.6      72.8      72.9      73.1   
1      1.0        6.0      0.100      72.5      72.7      72.8      73.0   
2      1.0        6.0      0.000      72.7      72.8      73.0      73.1   
3      1.0        1.0      0.001     111.0     112.0     114.0     116.0   
4      1.0        1.0      0.010     110.0     112.0     113.0     116.0   
5      1.0        1.0      0.100     110.0     112.0     113.0     116.0   
6      1.0        1.0      1.000     111.0     112.0     114.0     116.0   
7      1.0        1.0      0.000     111.0     112.0     114.0     117.0   
8      1.0        2.0      0.001      69.3      70.5      72.0      74.0   
9      1.0        2.0      0.010      69.3      70.5      72.0      73.9   
10     1.0        2.0      0.100      69.6      70.8      72.3      74.2   
11     1.0        2.0      1.000      70.4      71.5      73.0      74.9   
12     1.0  

Sensor  Electrode  microg/ml  1.00E+06  7.94E+05  6.31E+05  5.01E+05  \
0     1.0        6.0      0.001      72.6      72.8      72.9      73.1   
1     1.0        6.0      0.100      72.5      72.7      72.8      73.0   
2     1.0        6.0      0.000      72.7      72.8      73.0      73.1   
3     1.0        1.0      0.001     111.0     112.0     114.0     116.0   
4     1.0        1.0      0.010     110.0     112.0     113.0     116.0   

   3.98E+05  3.16E+05  2.51E+05  ...  7.94E+00  6.31E+00  5.01E+00  3.98E+00  \
0      73.4      73.8      74.4  ...   16900.0   21000.0   25900.0   31700.0   
1      73.3      73.7      74.3  ...   16800.0   20700.0   25500.0   31200.0   
2      73.4      73.9      74.6  ...   17400.0   21300.0   26200.0   32000.0   
3     119.0     123.0     128.0  ...  182000.0  220000.0  259000.0  298000.0   
4     118.0     122.0     127.0  ...  169000.0  204000.0  242000.0  281000.0   

   3.16E+00  2.51E+00  2.00E+00  1.58E+00  1.26E+00  1.00E+00  
0   38600.0   46500.0   55400.0   65400.0   76500.0   88600.0  
1   37800.0   45700.0   54600.0   64800.0   76200.0   89100.0  
2   39000.0   47300.0   57100.0   68500.0   81400.0   96200.0  
3  337000.0  372000.0  402000.0  428000.0  449000.0  467000.0  
4  319000.0  353000.0  383000.0  411000.0  433000.0  451000.0  

[5 rows x 64 columns]

In [36]:
print(df.dtypes)

Sensor       float64
Electrode    float64
microg/ml    float64
1.00E+06     float64
7.94E+05     float64
              ...   
2.51E+00     float64
2.00E+00     float64
1.58E+00     float64
1.26E+00     float64
1.00E+00     float64
Length: 64, dtype: object


In [37]:
df_features = df.iloc[:,1:].copy()
X = df_features.to_numpy()
# X = df.values
X

array([[6.00e+00, 1.00e-03, 7.26e+01, ..., 6.54e+04, 7.65e+04, 8.86e+04],
       [6.00e+00, 1.00e-01, 7.25e+01, ..., 6.48e+04, 7.62e+04, 8.91e+04],
       [6.00e+00, 0.00e+00, 7.27e+01, ..., 6.85e+04, 8.14e+04, 9.62e+04],
       ...,
       [8.00e+00, 2.00e-01, 7.63e+01, ..., 3.97e+05, 4.90e+05, 5.97e+05],
       [8.00e+00, 1.00e+00, 7.67e+01, ..., 4.25e+05, 5.19e+05, 6.30e+05],
       [8.00e+00, 0.00e+00, 7.69e+01, ..., 4.45e+05, 5.44e+05, 6.57e+05]])

In [38]:
Y = df.iloc[:, 0].to_numpy()
Y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2.])

In [39]:
X.shape

(37, 63)

In [40]:
Y.shape

(37,)

In [41]:
# 2. PCA analysis
# 2.1 Load library

from sklearn.preprocessing import scale # Data scaling
from sklearn import decomposition # PCA
import pandas as pd # pandas

In [42]:
# 2.2 Data scaling
x = scale(X)

# Standardize the Data
# PCA is effected by scale so you need to scale the features in your data before applying PCA. Use StandardScaler to help you standardize the dataset’s features onto unit scale (mean = 0 and variance = 1) which is a requirement for the optimal performance of many machine learning algorithms.
x

array([[ 0.51986647, -0.54117499, -0.49312061, ..., -1.39828034,
        -1.44810094, -1.47363513],
       [ 0.51986647, -0.26477733, -0.49388058, ..., -1.402811  ,
        -1.45006259, -1.47089099],
       [ 0.51986647, -0.54396688, -0.49236063, ..., -1.37487192,
        -1.41606073, -1.43192414],
       ...,
       [ 1.30497093,  0.01441222, -0.46500156, ...,  1.10566495,
         1.25570062,  1.31661075],
       [ 1.30497093,  2.24792862, -0.46196166, ...,  1.31709579,
         1.44532636,  1.49772427],
       [ 1.30497093, -0.54396688, -0.46044171, ...,  1.46811782,
         1.60879683,  1.64590806]])

In [43]:
# 2.3 Perform PCA analysis
pca = decomposition.PCA(n_components=3)
pca.fit(x) # when build the model we use pca.fit function. Where by the argument will be the input data, which essencially is the x variable
# we are using the x variable because pca is an unsupervised learning approach, meaning that it does not need the y variable or the class label in order to learn
# it`ll goind to cluster the data based on similarity and differences, based on the eigenvalue that are inherently present in the data set

PCA(n_components=3)

In [44]:
# 2.4 compure the scores value
# scores value will essentially be represented by the data samples so we`re gonna use the pca.transform function
scores = pca.transform(x)

In [45]:
scores

array([[-2.45291704, -9.40633471, -2.66671287],
       [-2.49426656, -9.41971287, -2.67735201],
       [-2.4776879 , -9.32778383, -2.71880151],
       [-3.87375125,  9.54801431, -0.69997047],
       [-3.67300048,  8.59735299, -0.49169749],
       [-3.83704127,  8.701534  , -0.52675189],
       [-3.85974188, 10.03486658, -0.03795322],
       [-4.13143106, 12.86998021,  0.44323171],
       [-1.34620879, -3.43014227,  2.74551131],
       [-1.60610524, -3.74791271,  2.37446462],
       [-1.71680655, -3.56575717,  2.41363927],
       [-1.62945706, -2.98727039,  2.87151018],
       [-1.51267285, -1.7626569 ,  2.99594162],
       [-2.07537664, -5.07876666, -2.05926578],
       [-2.04901955, -4.43838861, -1.78875353],
       [-2.40793462, -4.05480689, -2.21731755],
       [-2.40425045, -3.37894791, -2.05568858],
       [-2.35280974, -2.45419003, -2.08100553],
       [-0.6558032 , -2.27283895,  4.38324371],
       [-0.63775594, -2.30035829,  4.32518238],
       [-0.71764065, -2.24811925,  4.282

In [46]:
scores_df = pd.DataFrame(scores, columns=['PC1', 'PC2', 'PC3']) # dataframe is to make more readable
scores_df

PC1        PC2       PC3
0   -2.452917  -9.406335 -2.666713
1   -2.494267  -9.419713 -2.677352
2   -2.477688  -9.327784 -2.718802
3   -3.873751   9.548014 -0.699970
4   -3.673000   8.597353 -0.491697
5   -3.837041   8.701534 -0.526752
6   -3.859742  10.034867 -0.037953
7   -4.131431  12.869980  0.443232
8   -1.346209  -3.430142  2.745511
9   -1.606105  -3.747913  2.374465
10  -1.716807  -3.565757  2.413639
11  -1.629457  -2.987270  2.871510
12  -1.512673  -1.762657  2.995942
13  -2.075377  -5.078767 -2.059266
14  -2.049020  -4.438389 -1.788754
15  -2.407935  -4.054807 -2.217318
16  -2.404250  -3.378948 -2.055689
17  -2.352810  -2.454190 -2.081006
18  -0.655803  -2.272839  4.383244
19  -0.637756  -2.300358  4.325182
20  -0.717641  -2.248119  4.282550
21  -0.802604  -1.773123  4.522086
22  -1.021747  -0.348167  4.883225
23  10.733811  -0.040902 -0.995700
24  10.910998   0.150732 -0.842390
25  10.785678   0.673742 -0.851135
26  10.760746   1.121876 -0.815959
27  10.822423   1.710601 -0.529851
28  10.737851   2.214040 -0.438304
29  10.523469   3.478620 -0.296399
30  -3.388414   0.543486 -1.688720
31  -3.469975   0.813252 -1.712181
32  -3.460407   0.967146 -1.643089
33  -3.602308   1.125616 -1.761490
34  -3.691449   2.080168 -1.689240
35  -3.838872   3.263610 -1.390997
36  -4.087521   4.141540 -1.563859

In [47]:
y_label = []

for i in Y:
    if i == 1:
        y_label.append('HCV')
    else:
        y_label.append('HIV')

sensors = pd.DataFrame(y_label, columns=['Sensor'])

In [48]:
df_scores = pd.concat([scores_df, sensors], axis=1) # combine dataframes with concat
df_scores

PC1        PC2       PC3 Sensor
0   -2.452917  -9.406335 -2.666713    HCV
1   -2.494267  -9.419713 -2.677352    HCV
2   -2.477688  -9.327784 -2.718802    HCV
3   -3.873751   9.548014 -0.699970    HCV
4   -3.673000   8.597353 -0.491697    HCV
5   -3.837041   8.701534 -0.526752    HCV
6   -3.859742  10.034867 -0.037953    HCV
7   -4.131431  12.869980  0.443232    HCV
8   -1.346209  -3.430142  2.745511    HCV
9   -1.606105  -3.747913  2.374465    HCV
10  -1.716807  -3.565757  2.413639    HCV
11  -1.629457  -2.987270  2.871510    HCV
12  -1.512673  -1.762657  2.995942    HCV
13  -2.075377  -5.078767 -2.059266    HCV
14  -2.049020  -4.438389 -1.788754    HCV
15  -2.407935  -4.054807 -2.217318    HCV
16  -2.404250  -3.378948 -2.055689    HCV
17  -2.352810  -2.454190 -2.081006    HCV
18  -0.655803  -2.272839  4.383244    HCV
19  -0.637756  -2.300358  4.325182    HCV
20  -0.717641  -2.248119  4.282550    HCV
21  -0.802604  -1.773123  4.522086    HCV
22  -1.021747  -0.348167  4.883225    HCV
23  10.733811  -0.040902 -0.995700    HIV
24  10.910998   0.150732 -0.842390    HIV
25  10.785678   0.673742 -0.851135    HIV
26  10.760746   1.121876 -0.815959    HIV
27  10.822423   1.710601 -0.529851    HIV
28  10.737851   2.214040 -0.438304    HIV
29  10.523469   3.478620 -0.296399    HIV
30  -3.388414   0.543486 -1.688720    HIV
31  -3.469975   0.813252 -1.712181    HIV
32  -3.460407   0.967146 -1.643089    HIV
33  -3.602308   1.125616 -1.761490    HIV
34  -3.691449   2.080168 -1.689240    HIV
35  -3.838872   3.263610 -1.390997    HIV
36  -4.087521   4.141540 -1.563859    HIV

In [49]:
feature_names = df.columns[1:]
feature_names

Index(['Electrode', 'microg/ml', '1.00E+06', '7.94E+05', '6.31E+05',
       '5.01E+05', '3.98E+05', '3.16E+05', '2.51E+05', '2.00E+05', '1.58E+05',
       '1.26E+05', '1.00E+05', '7.94E+04', '6.31E+04', '5.01E+04', '3.98E+04',
       '3.16E+04', '2.51E+04', '2.00E+04', '1.58E+04', '1.26E+04', '1.00E+04',
       '7.94E+03', '6.31E+03', '5.01E+03', '3.98E+03', '3.16E+03', '2.51E+03',
       '2.00E+03', '1.58E+03', '1.26E+03', '1.00E+03', '7.94E+02', '6.31E+02',
       '5.01E+02', '3.98E+02', '3.16E+02', '2.51E+02', '2.00E+02', '1.58E+02',
       '1.26E+02', '1.00E+02', '7.94E+01', '6.31E+01', '5.01E+01', '3.98E+01',
       '3.16E+01', '2.51E+01', '2.00E+01', '1.58E+01', '1.26E+01', '1.00E+01',
       '7.94E+00', '6.31E+00', '5.01E+00', '3.98E+00', '3.16E+00', '2.51E+00',
       '2.00E+00', '1.58E+00', '1.26E+00', '1.00E+00'],
      dtype='object')

In [50]:
# 2.5 retrieve the loading values (remember PCA scores and loadings)
# loadings value tell about the descriptor and scores value tell about the data samples
# 150 flowers 150 score values 4 descriptors 4 loading values (1 for each descriptor)
loadings = pca.components_.T
df_loadings = pd.DataFrame(loadings, columns=['PC1', 'PC2', 'PC3'], index=feature_names)
df_loadings

PC1       PC2       PC3
Electrode  0.073340 -0.030337 -0.171864
microg/ml -0.001687  0.020893  0.039349
1.00E+06   0.180942  0.043794 -0.060339
7.94E+05   0.180910  0.044051 -0.059913
6.31E+05   0.180873  0.044417 -0.059244
...             ...       ...       ...
2.51E+00  -0.049126  0.168616 -0.176537
2.00E+00  -0.042379  0.161531 -0.202195
1.58E+00  -0.031837  0.149784 -0.228360
1.26E+00  -0.022371  0.134069 -0.247944
1.00E+00  -0.011614  0.114059 -0.263809

[63 rows x 3 columns]

In [51]:
# 2.6 explained variance
# what`s the contribuition to the percent variance of the entire model contributed by each of the principal components
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.44513476, 0.41913929, 0.08710505])

In [52]:
# 3. Scree plot
import numpy as np
import plotly.express as px

In [53]:
# 3.1 preparing the explained variance data
# add origin value, x and y are going to have origin zero, the subsequent lines of code are going to create the scree plot
# the scree plot does not start from zero, then we need to manually create the zero origin
explained_variance = np.insert(explained_variance, 0, 0)
explained_variance

array([0.        , 0.44513476, 0.41913929, 0.08710505])

In [54]:
# 3.2 Preparing cumulative variance data
cumulative_variance = np.cumsum(np.round(explained_variance, decimals=3))

In [55]:
# 3.3 Combining dataframe
pc_df = pd.DataFrame(['', 'PC1', 'PC2', 'PC3'], columns=['PC'])
explained_variance_df = pd.DataFrame(explained_variance, columns=['Explained Variance'])
cumulative_variance_df = pd.DataFrame(cumulative_variance, columns=['Cumulative Variance'])

In [56]:
df_explained_variance = pd.concat([pc_df, explained_variance_df, cumulative_variance_df], axis=1)
df_explained_variance

PC  Explained Variance  Cumulative Variance
0                 0.000000                0.000
1  PC1            0.445135                0.445
2  PC2            0.419139                0.864
3  PC3            0.087105                0.951

In [57]:
# 3.4 Creating Scree Plot
# https://plotly.com/python/bar-charts/

fig = px.bar(df_explained_variance, x='PC', y='Explained Variance', text='Explained Variance', width=800)

In [58]:
fig.update_traces(texttemplate='%{text:.3f}', textposition='outside') # limit decimal cases and text outside the bar
fig.show() #explained variance

In [59]:
# explained variance + cumulative variance
# https://plotly.com/python/creating-and-updating-figures

import plotly.graph_objects as go
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ))

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ))

fig.show()

In [60]:
# Explained variance + cumulative variance (Separate Plot)

from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=1, cols=2)

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ), row=1, col=1
)

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ), row=1, col=2
)

fig.show()

In [61]:
# 4. Scores plot
# check API documentation for plotly.express https://plotly.com/python/3d-scatter-plots

import plotly.express as px

fig = px.scatter_3d(df_scores, x='PC1', y='PC2', z='PC3', color='Sensor')
fig.show()

In [62]:
# 4.1 Customize 3D Scatter Plot

fig = px.scatter_3d(df_scores, x='PC1', y='PC2', z='PC3', color='Sensor', symbol='Sensor', opacity=0.4)

# tight layout
fig.update_layout(margin=dict(l=0, r=0, b=0, t=0)) # left, right, bottom, top with zero margin

fig.show()

# https://plotly.com/python/templates/
# fig.update_layout(template='plotly_white')
# plotly, plotly_white, plotly_dark, ggplot2, seaborn, simple_white, none

In [65]:
# 5. Loadings Plot

loadings_label = df_loadings.index
# loadings_label = df_loadings.index.str.strip(' (cm)')

fig = px.scatter_3d(df_loadings, x='PC1', y='PC2', z='PC3', text=loadings_label)
fig.show()

In [66]:
loadings_label

Index(['Electrode', 'microg/ml', '1.00E+06', '7.94E+05', '6.31E+05',
       '5.01E+05', '3.98E+05', '3.16E+05', '2.51E+05', '2.00E+05', '1.58E+05',
       '1.26E+05', '1.00E+05', '7.94E+04', '6.31E+04', '5.01E+04', '3.98E+04',
       '3.16E+04', '2.51E+04', '2.00E+04', '1.58E+04', '1.26E+04', '1.00E+04',
       '7.94E+03', '6.31E+03', '5.01E+03', '3.98E+03', '3.16E+03', '2.51E+03',
       '2.00E+03', '1.58E+03', '1.26E+03', '1.00E+03', '7.94E+02', '6.31E+02',
       '5.01E+02', '3.98E+02', '3.16E+02', '2.51E+02', '2.00E+02', '1.58E+02',
       '1.26E+02', '1.00E+02', '7.94E+01', '6.31E+01', '5.01E+01', '3.98E+01',
       '3.16E+01', '2.51E+01', '2.00E+01', '1.58E+01', '1.26E+01', '1.00E+01',
       '7.94E+00', '6.31E+00', '5.01E+00', '3.98E+00', '3.16E+00', '2.51E+00',
       '2.00E+00', '1.58E+00', '1.26E+00', '1.00E+00'],
      dtype='object')

In [67]:
df_loadings

PC1       PC2       PC3
Electrode  0.073340 -0.030337 -0.171864
microg/ml -0.001687  0.020893  0.039349
1.00E+06   0.180942  0.043794 -0.060339
7.94E+05   0.180910  0.044051 -0.059913
6.31E+05   0.180873  0.044417 -0.059244
...             ...       ...       ...
2.51E+00  -0.049126  0.168616 -0.176537
2.00E+00  -0.042379  0.161531 -0.202195
1.58E+00  -0.031837  0.149784 -0.228360
1.26E+00  -0.022371  0.134069 -0.247944
1.00E+00  -0.011614  0.114059 -0.263809

[63 rows x 3 columns]

In [68]:
df_loadings.sort_values(by='PC1',ascending=False)

PC1       PC2       PC3
1.00E+04  0.182307  0.045050 -0.016050
1.26E+04  0.182112  0.045600 -0.027318
7.94E+03  0.182063  0.046008 -0.000390
1.58E+04  0.181745  0.047136 -0.034890
2.00E+04  0.181240  0.049580 -0.039378
...            ...       ...       ...
6.31E+01 -0.072780  0.178370 -0.009477
1.58E+02 -0.072951  0.174984  0.071937
7.94E+01 -0.073812  0.178090  0.006944
1.26E+02 -0.074047  0.176492  0.047825
1.00E+02 -0.074322  0.177487  0.026114

[63 rows x 3 columns]

In [69]:
df_loadings.sort_values(by='PC2',ascending=False)

PC1       PC2       PC3
6.31E+01  -0.072780  0.178370 -0.009477
5.01E+01  -0.071821  0.178245 -0.024552
7.94E+01  -0.073812  0.178090  0.006944
3.98E+01  -0.070605  0.177911 -0.036813
1.00E+02  -0.074322  0.177487  0.026114
...             ...       ...       ...
6.31E+05   0.180873  0.044417 -0.059244
7.94E+05   0.180910  0.044051 -0.059913
1.00E+06   0.180942  0.043794 -0.060339
microg/ml -0.001687  0.020893  0.039349
Electrode  0.073340 -0.030337 -0.171864

[63 rows x 3 columns]

In [70]:
df_loadings.sort_values(by='PC3',ascending=False)

PC1       PC2       PC3
1.00E+03  0.029962  0.145995  0.268373
1.26E+03  0.062604  0.135114  0.268028
7.94E+02  0.002129  0.153524  0.255210
1.58E+03  0.095942  0.121076  0.250047
6.31E+02 -0.020812  0.158525  0.234552
...            ...       ...       ...
2.51E+00 -0.049126  0.168616 -0.176537
2.00E+00 -0.042379  0.161531 -0.202195
1.58E+00 -0.031837  0.149784 -0.228360
1.26E+00 -0.022371  0.134069 -0.247944
1.00E+00 -0.011614  0.114059 -0.263809

[63 rows x 3 columns]