In [35]:
# 1. PCA dataset
import pandas as pd

df = pd.read_csv('../../../mestrado/CalculosArtigo/Sensor/baseAllSensors78DZ1.csv')
print(df)

# df['Sensor'] = df['Sensor'].astype('string')
df.head()

    Sensor  Electrode  microg/ml  1.00E+06  7.94E+05  6.31E+05  5.01E+05  \
0      1.0        6.0      0.001      72.6      72.8      72.9      73.1   
1      1.0        6.0      0.100      72.5      72.7      72.8      73.0   
2      1.0        1.0      0.001     111.0     112.0     114.0     116.0   
3      1.0        1.0      0.010     110.0     112.0     113.0     116.0   
4      1.0        1.0      0.100     110.0     112.0     113.0     116.0   
5      1.0        1.0      1.000     111.0     112.0     114.0     116.0   
6      1.0        2.0      0.001      69.3      70.5      72.0      74.0   
7      1.0        2.0      0.010      69.3      70.5      72.0      73.9   
8      1.0        2.0      0.100      69.6      70.8      72.3      74.2   
9      1.0        2.0      1.000      70.4      71.5      73.0      74.9   
10     1.0        3.0      0.001      49.2      49.7      50.5      51.6   
11     1.0        3.0      0.010      49.1      49.7      50.4      51.4   
12     1.0  

Sensor  Electrode  microg/ml  1.00E+06  7.94E+05  6.31E+05  5.01E+05  \
0     1.0        6.0      0.001      72.6      72.8      72.9      73.1   
1     1.0        6.0      0.100      72.5      72.7      72.8      73.0   
2     1.0        1.0      0.001     111.0     112.0     114.0     116.0   
3     1.0        1.0      0.010     110.0     112.0     113.0     116.0   
4     1.0        1.0      0.100     110.0     112.0     113.0     116.0   

   3.98E+05  3.16E+05  2.51E+05  ...  7.94E+00  6.31E+00  5.01E+00  3.98E+00  \
0      73.4      73.8      74.4  ...   16900.0   21000.0   25900.0   31700.0   
1      73.3      73.7      74.3  ...   16800.0   20700.0   25500.0   31200.0   
2     119.0     123.0     128.0  ...  182000.0  220000.0  259000.0  298000.0   
3     118.0     122.0     127.0  ...  169000.0  204000.0  242000.0  281000.0   
4     119.0     122.0     127.0  ...  170000.0  206000.0  244000.0  283000.0   

   3.16E+00  2.51E+00  2.00E+00  1.58E+00  1.26E+00  1.00E+00  
0   38600.0   46500.0   55400.0   65400.0   76500.0   88600.0  
1   37800.0   45700.0   54600.0   64800.0   76200.0   89100.0  
2  337000.0  372000.0  402000.0  428000.0  449000.0  467000.0  
3  319000.0  353000.0  383000.0  411000.0  433000.0  451000.0  
4  320000.0  355000.0  386000.0  413000.0  435000.0  454000.0  

[5 rows x 64 columns]

In [36]:
print(df.dtypes)

Sensor       float64
Electrode    float64
microg/ml    float64
1.00E+06     float64
7.94E+05     float64
              ...   
2.51E+00     float64
2.00E+00     float64
1.58E+00     float64
1.26E+00     float64
1.00E+00     float64
Length: 64, dtype: object


In [37]:
df_features = df.iloc[:,1:].copy()
X = df_features.to_numpy()
# X = df.values
X

array([[6.00e+00, 1.00e-03, 7.26e+01, ..., 6.54e+04, 7.65e+04, 8.86e+04],
       [6.00e+00, 1.00e-01, 7.25e+01, ..., 6.48e+04, 7.62e+04, 8.91e+04],
       [1.00e+00, 1.00e-03, 1.11e+02, ..., 4.28e+05, 4.49e+05, 4.67e+05],
       ...,
       [8.00e+00, 1.00e-01, 7.58e+01, ..., 3.76e+05, 4.53e+05, 5.64e+05],
       [8.00e+00, 2.00e-01, 7.63e+01, ..., 3.97e+05, 4.90e+05, 5.97e+05],
       [8.00e+00, 1.00e+00, 7.67e+01, ..., 4.25e+05, 5.19e+05, 6.30e+05]])

In [38]:
Y = df.iloc[:, 0].to_numpy()
Y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [39]:
X.shape

(30, 63)

In [40]:
Y.shape

(30,)

In [41]:
# 2. PCA analysis
# 2.1 Load library

from sklearn.preprocessing import scale # Data scaling
from sklearn import decomposition # PCA
import pandas as pd # pandas

In [42]:
# 2.2 Data scaling
x = scale(X)

# Standardize the Data
# PCA is effected by scale so you need to scale the features in your data before applying PCA. Use StandardScaler to help you standardize the dataset’s features onto unit scale (mean = 0 and variance = 1) which is a requirement for the optimal performance of many machine learning algorithms.
x

array([[ 0.49321543, -0.62350062, -0.50932933, ..., -1.4174654 ,
        -1.47559018, -1.50369558],
       [ 0.49321543, -0.36555427, -0.5100752 , ..., -1.42213341,
        -1.47762448, -1.50086472],
       [-1.45368757, -0.62350062, -0.22291549, ...,  1.40356512,
         1.05033125,  0.63869836],
       ...,
       [ 1.27197662, -0.36555427, -0.48546151, ...,  0.99900476,
         1.07745524,  1.18788497],
       [ 1.27197662, -0.1050024 , -0.48173217, ...,  1.16238491,
         1.32835213,  1.37472165],
       [ 1.27197662,  1.97941253, -0.47874869, ...,  1.3802251 ,
         1.52500105,  1.56155833]])

In [43]:
# 2.3 Perform PCA analysis
pca = decomposition.PCA(n_components=3)
pca.fit(x) # when build the model we use pca.fit function. Where by the argument will be the input data, which essencially is the x variable
# we are using the x variable because pca is an unsupervised learning approach, meaning that it does not need the y variable or the class label in order to learn
# it`ll goind to cluster the data based on similarity and differences, based on the eigenvalue that are inherently present in the data set

PCA(n_components=3)

In [44]:
# 2.4 compure the scores value
# scores value will essentially be represented by the data samples so we`re gonna use the pca.transform function
scores = pca.transform(x)

In [45]:
scores

array([[-1.27711359e-01,  9.94274995e+00, -3.09706885e+00],
       [-1.67635424e-01,  9.96287957e+00, -3.10394181e+00],
       [-6.55402658e+00, -9.06358219e+00, -4.05858702e-01],
       [-6.10208673e+00, -8.13866779e+00, -2.12572804e-01],
       [-6.29359591e+00, -8.21234714e+00, -2.39961452e-01],
       [-6.67877784e+00, -9.58566429e+00,  3.45084469e-01],
       [-5.46890573e-01,  3.60871472e+00,  2.83486351e+00],
       [-7.23530066e-01,  3.98822460e+00,  2.43810535e+00],
       [-8.80047109e-01,  3.82385387e+00,  2.49275097e+00],
       [-9.55253882e-01,  3.19653891e+00,  3.02811772e+00],
       [-8.70134243e-01,  5.47872753e+00, -2.31976752e+00],
       [-1.00725413e+00,  4.82067871e+00, -2.01644904e+00],
       [-1.46825337e+00,  4.50605809e+00, -2.44367598e+00],
       [-1.65191220e+00,  3.80008054e+00, -2.21749578e+00],
       [-1.66986251e-01,  2.26879993e+00,  4.58831348e+00],
       [-1.42383527e-01,  2.29334579e+00,  4.52413112e+00],
       [-2.38646525e-01,  2.25520550e+00

In [46]:
scores_df = pd.DataFrame(scores, columns=['PC1', 'PC2', 'PC3']) # dataframe is to make more readable
scores_df

PC1       PC2       PC3
0   -0.127711  9.942750 -3.097069
1   -0.167635  9.962880 -3.103942
2   -6.554027 -9.063582 -0.405859
3   -6.102087 -8.138668 -0.212573
4   -6.293596 -8.212347 -0.239961
5   -6.678778 -9.585664  0.345084
6   -0.546891  3.608715  2.834864
7   -0.723530  3.988225  2.438105
8   -0.880047  3.823854  2.492751
9   -0.955254  3.196539  3.028118
10  -0.870134  5.478728 -2.319768
11  -1.007254  4.820679 -2.016449
12  -1.468253  4.506058 -2.443676
13  -1.651912  3.800081 -2.217496
14  -0.166986  2.268800  4.588313
15  -0.142384  2.293346  4.524131
16  -0.238647  2.255206  4.485142
17  -0.461130  1.770282  4.786424
18  10.174481 -2.495654 -0.981327
19  10.301850 -2.728015 -0.817925
20  10.040846 -3.233863 -0.805350
21   9.897650 -3.686220 -0.748974
22   9.806418 -4.301452 -0.425636
23   9.580997 -4.812110 -0.281417
24  -3.690251 -0.005341 -1.642764
25  -3.847115 -0.263334 -1.663257
26  -3.879146 -0.422743 -1.587486
27  -4.065431 -0.555390 -1.707109
28  -4.407935 -1.510508 -1.594049
29  -4.876108 -2.701246 -1.210846

In [47]:
y_label = []

for i in Y:
    if i == 1:
        y_label.append('HCV')
    else:
        y_label.append('HIV')

sensors = pd.DataFrame(y_label, columns=['Sensor'])

In [48]:
df_scores = pd.concat([scores_df, sensors], axis=1) # combine dataframes with concat
df_scores

PC1       PC2       PC3 Sensor
0   -0.127711  9.942750 -3.097069    HCV
1   -0.167635  9.962880 -3.103942    HCV
2   -6.554027 -9.063582 -0.405859    HCV
3   -6.102087 -8.138668 -0.212573    HCV
4   -6.293596 -8.212347 -0.239961    HCV
5   -6.678778 -9.585664  0.345084    HCV
6   -0.546891  3.608715  2.834864    HCV
7   -0.723530  3.988225  2.438105    HCV
8   -0.880047  3.823854  2.492751    HCV
9   -0.955254  3.196539  3.028118    HCV
10  -0.870134  5.478728 -2.319768    HCV
11  -1.007254  4.820679 -2.016449    HCV
12  -1.468253  4.506058 -2.443676    HCV
13  -1.651912  3.800081 -2.217496    HCV
14  -0.166986  2.268800  4.588313    HCV
15  -0.142384  2.293346  4.524131    HCV
16  -0.238647  2.255206  4.485142    HCV
17  -0.461130  1.770282  4.786424    HCV
18  10.174481 -2.495654 -0.981327    HIV
19  10.301850 -2.728015 -0.817925    HIV
20  10.040846 -3.233863 -0.805350    HIV
21   9.897650 -3.686220 -0.748974    HIV
22   9.806418 -4.301452 -0.425636    HIV
23   9.580997 -4.812110 -0.281417    HIV
24  -3.690251 -0.005341 -1.642764    HIV
25  -3.847115 -0.263334 -1.663257    HIV
26  -3.879146 -0.422743 -1.587486    HIV
27  -4.065431 -0.555390 -1.707109    HIV
28  -4.407935 -1.510508 -1.594049    HIV
29  -4.876108 -2.701246 -1.210846    HIV

In [49]:
feature_names = df.columns[1:]
feature_names

Index(['Electrode', 'microg/ml', '1.00E+06', '7.94E+05', '6.31E+05',
       '5.01E+05', '3.98E+05', '3.16E+05', '2.51E+05', '2.00E+05', '1.58E+05',
       '1.26E+05', '1.00E+05', '7.94E+04', '6.31E+04', '5.01E+04', '3.98E+04',
       '3.16E+04', '2.51E+04', '2.00E+04', '1.58E+04', '1.26E+04', '1.00E+04',
       '7.94E+03', '6.31E+03', '5.01E+03', '3.98E+03', '3.16E+03', '2.51E+03',
       '2.00E+03', '1.58E+03', '1.26E+03', '1.00E+03', '7.94E+02', '6.31E+02',
       '5.01E+02', '3.98E+02', '3.16E+02', '2.51E+02', '2.00E+02', '1.58E+02',
       '1.26E+02', '1.00E+02', '7.94E+01', '6.31E+01', '5.01E+01', '3.98E+01',
       '3.16E+01', '2.51E+01', '2.00E+01', '1.58E+01', '1.26E+01', '1.00E+01',
       '7.94E+00', '6.31E+00', '5.01E+00', '3.98E+00', '3.16E+00', '2.51E+00',
       '2.00E+00', '1.58E+00', '1.26E+00', '1.00E+00'],
      dtype='object')

In [50]:
# 2.5 retrieve the loading values (remember PCA scores and loadings)
# loadings value tell about the descriptor and scores value tell about the data samples
# 150 flowers 150 score values 4 descriptors 4 loading values (1 for each descriptor)
loadings = pca.components_.T
df_loadings = pd.DataFrame(loadings, columns=['PC1', 'PC2', 'PC3'], index=feature_names)
df_loadings

PC1       PC2       PC3
Electrode  0.074819  0.005856 -0.165968
microg/ml -0.012442 -0.030171  0.058978
1.00E+06   0.162847 -0.088776 -0.058044
7.94E+05   0.162746 -0.089041 -0.057640
6.31E+05   0.162658 -0.089327 -0.057003
...             ...       ...       ...
2.51E+00  -0.088400 -0.154322 -0.169435
2.00E+00  -0.081360 -0.148285 -0.196405
1.58E+00  -0.069770 -0.138724 -0.224015
1.26E+00  -0.056787 -0.126841 -0.244033
1.00E+00  -0.041959 -0.107811 -0.262953

[63 rows x 3 columns]

In [51]:
# 2.6 explained variance
# what`s the contribuition to the percent variance of the entire model contributed by each of the principal components
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.46218298, 0.39986102, 0.09093568])

In [52]:
# 3. Scree plot
import numpy as np
import plotly.express as px

In [53]:
# 3.1 preparing the explained variance data
# add origin value, x and y are going to have origin zero, the subsequent lines of code are going to create the scree plot
# the scree plot does not start from zero, then we need to manually create the zero origin
explained_variance = np.insert(explained_variance, 0, 0)
explained_variance

array([0.        , 0.46218298, 0.39986102, 0.09093568])

In [54]:
# 3.2 Preparing cumulative variance data
cumulative_variance = np.cumsum(np.round(explained_variance, decimals=3))

In [55]:
# 3.3 Combining dataframe
pc_df = pd.DataFrame(['', 'PC1', 'PC2', 'PC3'], columns=['PC'])
explained_variance_df = pd.DataFrame(explained_variance, columns=['Explained Variance'])
cumulative_variance_df = pd.DataFrame(cumulative_variance, columns=['Cumulative Variance'])

In [56]:
df_explained_variance = pd.concat([pc_df, explained_variance_df, cumulative_variance_df], axis=1)
df_explained_variance

PC  Explained Variance  Cumulative Variance
0                 0.000000                0.000
1  PC1            0.462183                0.462
2  PC2            0.399861                0.862
3  PC3            0.090936                0.953

In [57]:
# 3.4 Creating Scree Plot
# https://plotly.com/python/bar-charts/

fig = px.bar(df_explained_variance, x='PC', y='Explained Variance', text='Explained Variance', width=800)

In [58]:
fig.update_traces(texttemplate='%{text:.3f}', textposition='outside') # limit decimal cases and text outside the bar
fig.show() #explained variance

In [59]:
# explained variance + cumulative variance
# https://plotly.com/python/creating-and-updating-figures

import plotly.graph_objects as go
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ))

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ))

fig.show()

In [60]:
# Explained variance + cumulative variance (Separate Plot)

from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=1, cols=2)

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ), row=1, col=1
)

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ), row=1, col=2
)

fig.show()

In [61]:
# 4. Scores plot
# check API documentation for plotly.express https://plotly.com/python/3d-scatter-plots

import plotly.express as px

fig = px.scatter_3d(df_scores, x='PC1', y='PC2', z='PC3', color='Sensor')
fig.show()

In [62]:
# 4.1 Customize 3D Scatter Plot

fig = px.scatter_3d(df_scores, x='PC1', y='PC2', z='PC3', color='Sensor', symbol='Sensor', opacity=0.4)

# tight layout
fig.update_layout(margin=dict(l=0, r=0, b=0, t=0)) # left, right, bottom, top with zero margin

fig.show()

# https://plotly.com/python/templates/
# fig.update_layout(template='plotly_white')
# plotly, plotly_white, plotly_dark, ggplot2, seaborn, simple_white, none

In [63]:
# 5. Loadings Plot

loadings_label = df_loadings.index
# loadings_label = df_loadings.index.str.strip(' (cm)')

fig = px.scatter_3d(df_loadings, x='PC1', y='PC2', z='PC3', text=loadings_label)
fig.show()

In [64]:
loadings_label

Index(['Electrode', 'microg/ml', '1.00E+06', '7.94E+05', '6.31E+05',
       '5.01E+05', '3.98E+05', '3.16E+05', '2.51E+05', '2.00E+05', '1.58E+05',
       '1.26E+05', '1.00E+05', '7.94E+04', '6.31E+04', '5.01E+04', '3.98E+04',
       '3.16E+04', '2.51E+04', '2.00E+04', '1.58E+04', '1.26E+04', '1.00E+04',
       '7.94E+03', '6.31E+03', '5.01E+03', '3.98E+03', '3.16E+03', '2.51E+03',
       '2.00E+03', '1.58E+03', '1.26E+03', '1.00E+03', '7.94E+02', '6.31E+02',
       '5.01E+02', '3.98E+02', '3.16E+02', '2.51E+02', '2.00E+02', '1.58E+02',
       '1.26E+02', '1.00E+02', '7.94E+01', '6.31E+01', '5.01E+01', '3.98E+01',
       '3.16E+01', '2.51E+01', '2.00E+01', '1.58E+01', '1.26E+01', '1.00E+01',
       '7.94E+00', '6.31E+00', '5.01E+00', '3.98E+00', '3.16E+00', '2.51E+00',
       '2.00E+00', '1.58E+00', '1.26E+00', '1.00E+00'],
      dtype='object')

In [65]:
df_loadings

PC1       PC2       PC3
Electrode  0.074819  0.005856 -0.165968
microg/ml -0.012442 -0.030171  0.058978
1.00E+06   0.162847 -0.088776 -0.058044
7.94E+05   0.162746 -0.089041 -0.057640
6.31E+05   0.162658 -0.089327 -0.057003
...             ...       ...       ...
2.51E+00  -0.088400 -0.154322 -0.169435
2.00E+00  -0.081360 -0.148285 -0.196405
1.58E+00  -0.069770 -0.138724 -0.224015
1.26E+00  -0.056787 -0.126841 -0.244033
1.00E+00  -0.041959 -0.107811 -0.262953

[63 rows x 3 columns]

In [66]:
df_loadings.sort_values(by='PC1',ascending=False)

PC1       PC2       PC3
1.00E+04  0.165878 -0.085734 -0.019867
7.94E+03  0.165727 -0.086216 -0.004822
1.26E+04  0.165356 -0.086607 -0.030340
6.31E+03  0.164654 -0.088092  0.015874
1.58E+04  0.164553 -0.088285 -0.037325
...            ...       ...       ...
6.31E+01 -0.113544 -0.156221 -0.010509
1.58E+02 -0.114521 -0.151140  0.071680
7.94E+01 -0.114866 -0.155319  0.005751
1.26E+02 -0.115559 -0.152801  0.047159
1.00E+02 -0.115616 -0.154186  0.025028

[63 rows x 3 columns]

In [67]:
df_loadings.sort_values(by='PC2',ascending=False)

PC1       PC2       PC3
Electrode  0.074819  0.005856 -0.165968
microg/ml -0.012442 -0.030171  0.058978
1.00E+04   0.165878 -0.085734 -0.019867
7.94E+03   0.165727 -0.086216 -0.004822
1.26E+04   0.165356 -0.086607 -0.030340
...             ...       ...       ...
3.16E+01  -0.109087 -0.157058 -0.046913
2.51E+01  -0.107439 -0.157096 -0.055337
6.31E+00  -0.100143 -0.157166 -0.098586
5.01E+00  -0.098450 -0.157505 -0.111858
3.98E+00  -0.096322 -0.157522 -0.127305

[63 rows x 3 columns]

In [68]:
df_loadings.sort_values(by='PC3',ascending=False)

PC1       PC2       PC3
1.00E+03 -0.001696 -0.146528  0.278416
1.26E+03  0.035293 -0.143180  0.275738
7.94E+02 -0.032943 -0.146934  0.265731
1.58E+03  0.072690 -0.136479  0.253334
6.31E+02 -0.058202 -0.146197  0.243647
...            ...       ...       ...
2.51E+00 -0.088400 -0.154322 -0.169435
2.00E+00 -0.081360 -0.148285 -0.196405
1.58E+00 -0.069770 -0.138724 -0.224015
1.26E+00 -0.056787 -0.126841 -0.244033
1.00E+00 -0.041959 -0.107811 -0.262953

[63 rows x 3 columns]