In [1]:
# 1. PCA dataset
import pandas as pd

df = pd.read_csv('../../../mestrado/CalculosArtigo/Eletrodo/HCV/baseSensorsHCVDefesa.csv')
print(df)

# df['Sensor'] = df['Sensor'].astype('string')
df.head()

    Electrode  Param  microg/ml      1.00E+06      7.94E+05      6.31E+05  \
0         1.0    1.0      0.002  4.060000e+02  4.080000e+02  4.100000e+02   
1         1.0    1.0      0.010  4.060000e+02  4.080000e+02  4.100000e+02   
2         1.0    1.0      0.020  4.060000e+02  4.090000e+02  4.100000e+02   
3         1.0    1.0      0.100  4.070000e+02  4.090000e+02  4.110000e+02   
4         1.0    1.0      0.200  4.080000e+02  4.100000e+02  4.120000e+02   
..        ...    ...        ...           ...           ...           ...   
91        2.0    6.0      0.200 -1.550000e-07  3.270000e-08  1.730000e-08   
92        2.0    6.0      1.000 -2.390000e-07  3.020000e-08  1.660000e-08   
93        2.0    6.0      0.000 -3.180000e-07  2.880000e-08  1.610000e-08   
94        3.0    6.0      0.002  3.190000e-08  1.360000e-08  9.550000e-09   
95        3.0    6.0      0.000  3.220000e-08  1.360000e-08  9.560000e-09   

        5.01E+05      3.98E+05      3.16E+05      2.51E+05  ...      7.94E+

Electrode  Param  microg/ml  1.00E+06  7.94E+05  6.31E+05  5.01E+05  \
0        1.0    1.0      0.002     406.0     408.0     410.0     412.0   
1        1.0    1.0      0.010     406.0     408.0     410.0     412.0   
2        1.0    1.0      0.020     406.0     409.0     410.0     412.0   
3        1.0    1.0      0.100     407.0     409.0     411.0     413.0   
4        1.0    1.0      0.200     408.0     410.0     412.0     414.0   

   3.98E+05  3.16E+05  2.51E+05  ...  7.94E+00  6.31E+00  5.01E+00  3.98E+00  \
0     414.0     417.0     420.0  ...   39100.0   49500.0   63400.0   80700.0   
1     414.0     416.0     419.0  ...   39400.0   50000.0   64100.0   81200.0   
2     414.0     417.0     420.0  ...   42900.0   53800.0   70100.0   89400.0   
3     415.0     417.0     420.0  ...   45600.0   57800.0   73800.0   94600.0   
4     416.0     418.0     421.0  ...   48400.0   61700.0   79100.0  100000.0   

   3.16E+00  2.51E+00  2.00E+00  1.58E+00  1.26E+00  1.00E+00  
0  102000.0  132000.0  164000.0  210000.0  258000.0  340000.0  
1  105000.0  130000.0  165000.0  215000.0  270000.0  340000.0  
2  116000.0  145000.0  183000.0  235000.0  295000.0  359000.0  
3  120000.0  153000.0  195000.0  249000.0  307000.0  405000.0  
4  126000.0  163000.0  206000.0  261000.0  331000.0  393000.0  

[5 rows x 64 columns]

In [2]:
print(df.dtypes)

Electrode    float64
Param        float64
microg/ml    float64
1.00E+06     float64
7.94E+05     float64
              ...   
2.51E+00     float64
2.00E+00     float64
1.58E+00     float64
1.26E+00     float64
1.00E+00     float64
Length: 64, dtype: object


In [3]:
df_features = df.iloc[:,1:].copy()
X = df_features.to_numpy()
# X = df.values
X

array([[ 1.00e+00,  2.00e-03,  4.06e+02, ...,  2.10e+05,  2.58e+05,
         3.40e+05],
       [ 1.00e+00,  1.00e-02,  4.06e+02, ...,  2.15e+05,  2.70e+05,
         3.40e+05],
       [ 1.00e+00,  2.00e-02,  4.06e+02, ...,  2.35e+05,  2.95e+05,
         3.59e+05],
       ...,
       [ 6.00e+00,  0.00e+00, -3.18e-07, ...,  3.55e-08,  3.96e-08,
         4.35e-08],
       [ 6.00e+00,  2.00e-03,  3.19e-08, ...,  5.98e-08,  6.57e-08,
         7.18e-08],
       [ 6.00e+00,  0.00e+00,  3.22e-08, ...,  5.77e-08,  6.36e-08,
         7.14e-08]])

In [4]:
Y = df.iloc[:, 0].to_numpy()
Y

array([1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 3., 3., 1.,
       1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 3., 3., 1., 1.,
       1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 3., 3., 1., 1., 1.,
       1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 3., 3., 1., 1., 1., 1.,
       1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 3., 3., 1., 1., 1., 1., 1.,
       1., 1., 2., 2., 2., 2., 2., 2., 2., 3., 3.])

In [5]:
X.shape

(96, 63)

In [6]:
Y.shape

(96,)

In [7]:
# 2. PCA analysis
# 2.1 Load library

from sklearn.preprocessing import scale # Data scaling
from sklearn import decomposition # PCA
import pandas as pd # pandas

In [8]:
# 2.2 Data scaling
x = scale(X)

# Standardize the Data
# PCA is effected by scale so you need to scale the features in your data before applying PCA. Use StandardScaler to help you standardize the dataset’s features onto unit scale (mean = 0 and variance = 1) which is a requirement for the optimal performance of many machine learning algorithms.
x

array([[-1.46385011, -0.51159004,  0.2752031 , ..., -0.3557155 ,
        -0.3478737 , -0.33753939],
       [-1.46385011, -0.48672917,  0.2752031 , ..., -0.35551861,
        -0.34738013, -0.33753939],
       [-1.46385011, -0.45565309,  0.2752031 , ..., -0.35473104,
        -0.34635187, -0.33672025],
       ...,
       [ 1.46385011, -0.51780526,  0.27518912, ..., -0.36398498,
        -0.35848536, -0.35219768],
       [ 1.46385011, -0.51159004,  0.27518912, ..., -0.36398498,
        -0.35848536, -0.35219768],
       [ 1.46385011, -0.51780526,  0.27518912, ..., -0.36398498,
        -0.35848536, -0.35219768]])

In [9]:
# 2.3 Perform PCA analysis
pca = decomposition.PCA(n_components=3)
pca.fit(x) # when build the model we use pca.fit function. Where by the argument will be the input data, which essencially is the x variable
# we are using the x variable because pca is an unsupervised learning approach, meaning that it does not need the y variable or the class label in order to learn
# it`ll goind to cluster the data based on similarity and differences, based on the eigenvalue that are inherently present in the data set

PCA(n_components=3)

In [10]:
# 2.4 compure the scores value
# scores value will essentially be represented by the data samples so we`re gonna use the pca.transform function
scores = pca.transform(x)

In [11]:
scores

array([[-3.24942465e+00, -3.94651729e-02, -4.66239290e-01],
       [-3.24928125e+00, -3.98870138e-02, -4.41452461e-01],
       [-3.24862417e+00, -4.10951691e-02, -4.10492510e-01],
       [-3.24766445e+00, -4.46383317e-02, -1.62600021e-01],
       [-3.24681454e+00, -4.85192022e-02,  1.47287166e-01],
       [-3.24200541e+00, -7.69240264e-02,  2.62646803e+00],
       [-3.24616539e+00, -4.40796334e-02, -4.72602139e-01],
       [-3.24409444e+00, -4.71487184e-02, -4.66506870e-01],
       [-3.24395457e+00, -4.75474818e-02, -4.41718654e-01],
       [-3.24390624e+00, -4.78706404e-02, -4.10727119e-01],
       [-3.24335729e+00, -5.07895503e-02, -1.62810895e-01],
       [-3.24194839e+00, -5.54805152e-02,  1.47046779e-01],
       [-3.23683547e+00, -8.42797318e-02,  2.62621596e+00],
       [-3.24130255e+00, -5.09751371e-02, -4.72838011e-01],
       [-3.24351582e+00, -4.76257727e-02, -4.66510501e-01],
       [-3.24236782e+00, -4.92790387e-02, -4.72771002e-01],
       [-3.26657738e+00,  3.24989945e-02

In [12]:
scores_df = pd.DataFrame(scores, columns=['PC1', 'PC2', 'PC3']) # dataframe is to make more readable
scores_df

PC1       PC2       PC3
0  -3.249425 -0.039465 -0.466239
1  -3.249281 -0.039887 -0.441452
2  -3.248624 -0.041095 -0.410493
3  -3.247664 -0.044638 -0.162600
4  -3.246815 -0.048519  0.147287
..       ...       ...       ...
91 -3.092364 -0.030217  0.058568
92 -3.088130 -0.057777  2.537780
93 -3.093422 -0.023327 -0.561235
94 -3.093411 -0.023395 -0.555037
95 -3.093422 -0.023327 -0.561235

[96 rows x 3 columns]

In [32]:
y_label = []

for i in Y:
    if i == 1:
        y_label.append('SF_NS5A_1bic')
    elif i == 2:
        y_label.append('SF_NS5A_5bic')
    else:
        y_label.append('SF_NS5A_5bicp24')

sensors = pd.DataFrame(y_label, columns=['Sensor'])

In [33]:
df_scores = pd.concat([scores_df, sensors], axis=1) # combine dataframes with concat
df_scores

PC1       PC2       PC3           Sensor
0  -3.249425 -0.039465 -0.466239     SF_NS5A_1bic
1  -3.249281 -0.039887 -0.441452     SF_NS5A_1bic
2  -3.248624 -0.041095 -0.410493     SF_NS5A_1bic
3  -3.247664 -0.044638 -0.162600     SF_NS5A_1bic
4  -3.246815 -0.048519  0.147287     SF_NS5A_1bic
..       ...       ...       ...              ...
91 -3.092364 -0.030217  0.058568     SF_NS5A_5bic
92 -3.088130 -0.057777  2.537780     SF_NS5A_5bic
93 -3.093422 -0.023327 -0.561235     SF_NS5A_5bic
94 -3.093411 -0.023395 -0.555037  SF_NS5A_5bicp24
95 -3.093422 -0.023327 -0.561235  SF_NS5A_5bicp24

[96 rows x 4 columns]

In [34]:
feature_names = df.columns[1:]
feature_names

Index(['Param', 'microg/ml', '1.00E+06', '7.94E+05', '6.31E+05', '5.01E+05',
       '3.98E+05', '3.16E+05', '2.51E+05', '2.00E+05', '1.58E+05', '1.26E+05',
       '1.00E+05', '7.94E+04', '6.31E+04', '5.01E+04', '3.98E+04', '3.16E+04',
       '2.51E+04', '2.00E+04', '1.58E+04', '1.26E+04', '1.00E+04', '7.94E+03',
       '6.31E+03', '5.01E+03', '3.98E+03', '3.16E+03', '2.51E+03', '2.00E+03',
       '1.58E+03', '1.26E+03', '1.00E+03', '7.94E+02', '6.31E+02', '5.01E+02',
       '3.98E+02', '3.16E+02', '2.51E+02', '2.00E+02', '1.58E+02', '1.26E+02',
       '1.00E+02', '7.94E+01', '6.31E+01', '5.01E+01', '3.98E+01', '3.16E+01',
       '2.51E+01', '2.00E+01', '1.58E+01', '1.26E+01', '1.00E+01', '7.94E+00',
       '6.31E+00', '5.01E+00', '3.98E+00', '3.16E+00', '2.51E+00', '2.00E+00',
       '1.58E+00', '1.26E+00', '1.00E+00'],
      dtype='object')

In [35]:
# 2.5 retrieve the loading values (remember PCA scores and loadings)
# loadings value tell about the descriptor and scores value tell about the data samples
# 150 flowers 150 score values 4 descriptors 4 loading values (1 for each descriptor)
loadings = pca.components_.T
df_loadings = pd.DataFrame(loadings, columns=['PC1', 'PC2', 'PC3'], index=feature_names)
df_loadings

PC1       PC2       PC3
Param      0.055634  0.002156 -0.030449
microg/ml  0.001703 -0.011086  0.997235
1.00E+06  -0.087662  0.249300  0.005448
7.94E+05   0.007248  0.317167 -0.010988
6.31E+05   0.093916  0.230921 -0.020703
...             ...       ...       ...
2.51E+00   0.119136 -0.167571 -0.005722
2.00E+00   0.118133 -0.171238 -0.006158
1.58E+00   0.117361 -0.173915 -0.004723
1.26E+00   0.116179 -0.177895 -0.007426
1.00E+00   0.114946 -0.181616 -0.007399

[63 rows x 3 columns]

In [36]:
# 2.6 explained variance
# what`s the contribuition to the percent variance of the entire model contributed by each of the principal components
explained_variance = pca.explained_variance_ratio_
explained_variance

array([0.813204  , 0.15368422, 0.01591249])

In [37]:
# 3. Scree plot
import numpy as np
import plotly.express as px

In [38]:
# 3.1 preparing the explained variance data
# add origin value, x and y are going to have origin zero, the subsequent lines of code are going to create the scree plot
# the scree plot does not start from zero, then we need to manually create the zero origin
explained_variance = np.insert(explained_variance, 0, 0)
explained_variance

array([0.        , 0.813204  , 0.15368422, 0.01591249])

In [39]:
# 3.2 Preparing cumulative variance data
cumulative_variance = np.cumsum(np.round(explained_variance, decimals=3))

In [40]:
# 3.3 Combining dataframe
pc_df = pd.DataFrame(['', 'PC1', 'PC2', 'PC3'], columns=['PC'])
explained_variance_df = pd.DataFrame(explained_variance, columns=['Explained Variance'])
cumulative_variance_df = pd.DataFrame(cumulative_variance, columns=['Cumulative Variance'])

In [41]:
df_explained_variance = pd.concat([pc_df, explained_variance_df, cumulative_variance_df], axis=1)
df_explained_variance

PC  Explained Variance  Cumulative Variance
0                 0.000000                0.000
1  PC1            0.813204                0.813
2  PC2            0.153684                0.967
3  PC3            0.015912                0.983

In [42]:
# 3.4 Creating Scree Plot
# https://plotly.com/python/bar-charts/

fig = px.bar(df_explained_variance, x='PC', y='Explained Variance', text='Explained Variance', width=800)

In [43]:
fig.update_traces(texttemplate='%{text:.3f}', textposition='outside') # limit decimal cases and text outside the bar
fig.show() #explained variance

In [44]:
# explained variance + cumulative variance
# https://plotly.com/python/creating-and-updating-figures

import plotly.graph_objects as go
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ))

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ))

fig.show()

In [45]:
# Explained variance + cumulative variance (Separate Plot)

from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=1, cols=2)

fig.add_trace(
    go.Scatter(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Cumulative Variance'],
        marker=dict(size=15, color='LightSeaGreen')
    ), row=1, col=1
)

fig.add_trace(
    go.Bar(
        x=df_explained_variance['PC'],
        y=df_explained_variance['Explained Variance'],
        marker=dict(color='RoyalBlue')
    ), row=1, col=2
)

fig.show()

In [46]:
# 4. Scores plot
# check API documentation for plotly.express https://plotly.com/python/3d-scatter-plots

import plotly.express as px

fig = px.scatter_3d(df_scores, x='PC1', y='PC2', z='PC3', color='Sensor')
fig.show()

In [47]:
# 4.1 Customize 3D Scatter Plot

fig = px.scatter_3d(df_scores, x='PC1', y='PC2', z='PC3', color='Sensor', symbol='Sensor', opacity=0.4)

# tight layout
fig.update_layout(margin=dict(l=0, r=0, b=0, t=0)) # left, right, bottom, top with zero margin

fig.show()

# https://plotly.com/python/templates/
# fig.update_layout(template='plotly_white')
# plotly, plotly_white, plotly_dark, ggplot2, seaborn, simple_white, none

In [48]:
# 5. Loadings Plot

loadings_label = df_loadings.index
# loadings_label = df_loadings.index.str.strip(' (cm)')

fig = px.scatter_3d(df_loadings, x='PC1', y='PC2', z='PC3', text=loadings_label)
fig.show()

In [49]:
loadings_label

Index(['Param', 'microg/ml', '1.00E+06', '7.94E+05', '6.31E+05', '5.01E+05',
       '3.98E+05', '3.16E+05', '2.51E+05', '2.00E+05', '1.58E+05', '1.26E+05',
       '1.00E+05', '7.94E+04', '6.31E+04', '5.01E+04', '3.98E+04', '3.16E+04',
       '2.51E+04', '2.00E+04', '1.58E+04', '1.26E+04', '1.00E+04', '7.94E+03',
       '6.31E+03', '5.01E+03', '3.98E+03', '3.16E+03', '2.51E+03', '2.00E+03',
       '1.58E+03', '1.26E+03', '1.00E+03', '7.94E+02', '6.31E+02', '5.01E+02',
       '3.98E+02', '3.16E+02', '2.51E+02', '2.00E+02', '1.58E+02', '1.26E+02',
       '1.00E+02', '7.94E+01', '6.31E+01', '5.01E+01', '3.98E+01', '3.16E+01',
       '2.51E+01', '2.00E+01', '1.58E+01', '1.26E+01', '1.00E+01', '7.94E+00',
       '6.31E+00', '5.01E+00', '3.98E+00', '3.16E+00', '2.51E+00', '2.00E+00',
       '1.58E+00', '1.26E+00', '1.00E+00'],
      dtype='object')

In [50]:
df_loadings

PC1       PC2       PC3
Param      0.055634  0.002156 -0.030449
microg/ml  0.001703 -0.011086  0.997235
1.00E+06  -0.087662  0.249300  0.005448
7.94E+05   0.007248  0.317167 -0.010988
6.31E+05   0.093916  0.230921 -0.020703
...             ...       ...       ...
2.51E+00   0.119136 -0.167571 -0.005722
2.00E+00   0.118133 -0.171238 -0.006158
1.58E+00   0.117361 -0.173915 -0.004723
1.26E+00   0.116179 -0.177895 -0.007426
1.00E+00   0.114946 -0.181616 -0.007399

[63 rows x 3 columns]

In [51]:
df_loadings.sort_values(by='PC1',ascending=False)

PC1       PC2       PC3
3.98E+02   0.139560 -0.008875  0.005596
5.01E+02   0.139537  0.008990  0.005947
3.16E+02   0.139186 -0.025985  0.003347
6.31E+02   0.139022  0.027947  0.007793
2.51E+02   0.138465 -0.041973  0.002382
...             ...       ...       ...
6.31E+05   0.093916  0.230921 -0.020703
Param      0.055634  0.002156 -0.030449
7.94E+05   0.007248  0.317167 -0.010988
microg/ml  0.001703 -0.011086  0.997235
1.00E+06  -0.087662  0.249300  0.005448

[63 rows x 3 columns]

In [52]:
df_loadings.sort_values(by='PC2',ascending=False)

PC1       PC2       PC3
7.94E+05  0.007248  0.317167 -0.010988
1.00E+06 -0.087662  0.249300  0.005448
6.31E+05  0.093916  0.230921 -0.020703
5.01E+05  0.118123  0.163976 -0.020736
3.98E+05  0.125503  0.133910 -0.019618
...            ...       ...       ...
2.51E+00  0.119136 -0.167571 -0.005722
2.00E+00  0.118133 -0.171238 -0.006158
1.58E+00  0.117361 -0.173915 -0.004723
1.26E+00  0.116179 -0.177895 -0.007426
1.00E+00  0.114946 -0.181616 -0.007399

[63 rows x 3 columns]

In [53]:
df_loadings.sort_values(by='PC3',ascending=False)

PC1       PC2       PC3
microg/ml  0.001703 -0.011086  0.997235
3.16E+03   0.128822  0.121720  0.012113
2.51E+03   0.129974  0.115083  0.011762
3.98E+03   0.128023  0.126144  0.011512
2.00E+03   0.131468  0.105996  0.011285
...             ...       ...       ...
3.16E+05   0.128421  0.120367 -0.017477
3.98E+05   0.125503  0.133910 -0.019618
6.31E+05   0.093916  0.230921 -0.020703
5.01E+05   0.118123  0.163976 -0.020736
Param      0.055634  0.002156 -0.030449

[63 rows x 3 columns]